"""Canonical ecosystem catalog — seeded into DB; source of truth for contracts."""
from __future__ import annotations

SHARED_SERVICES = [
    {
        "code": "identity",
        "name": "Taifa Identity",
        "description": "Device-bound authentication and principal identity",
        "api_base": "/api/v1/auth/",
        "status": "production",
        "owner_team": "platform",
    },
    {
        "code": "payments",
        "name": "Taifa Payments",
        "description": "Double-entry payment engine and gateways",
        "api_base": "/api/v1/payments/",
        "status": "production",
        "owner_team": "payments",
    },
    {
        "code": "wallet",
        "name": "Taifa Wallet",
        "description": "Consumer and merchant wallet surfaces over Payments",
        "api_base": "/api/v1/payments/",
        "status": "production",
        "owner_team": "payments",
    },
    {
        "code": "notifications",
        "name": "Notifications",
        "description": "Push and in-app notification fabric",
        "api_base": "/api/v1/trips/notifications",
        "status": "production",
        "owner_team": "platform",
    },
    {
        "code": "registry",
        "name": "Taifa Registry",
        "description": "Eligibility and verification (Mobility Registry)",
        "api_base": "/api/v1/mobility-registry/",
        "status": "production",
        "owner_team": "mobility",
    },
    {
        "code": "gis",
        "name": "GIS",
        "description": "National and city map layers",
        "api_base": "/api/v1/trips/national/map",
        "status": "production",
        "owner_team": "mobility",
    },
    {
        "code": "ai",
        "name": "AI Platform",
        "description": "Shared AI capabilities (recommendations, fraud, OCR, …)",
        "api_base": "/api/v1/ai-os/",
        "status": "production",
        "owner_team": "platform",
    },
    {
        "code": "documents",
        "name": "Documents",
        "description": "Encrypted document vault (registry-scoped)",
        "api_base": "/api/v1/mobility-registry/",
        "status": "production",
        "owner_team": "mobility",
    },
    {
        "code": "reporting",
        "name": "Reporting",
        "description": "Regulatory and business reports",
        "api_base": "/api/v1/enterprise/",
        "status": "production",
        "owner_team": "enterprise",
    },
    {
        "code": "audit",
        "name": "Audit",
        "description": "Append-only audit and domain events",
        "api_base": "/api/v1/payments/",
        "status": "production",
        "owner_team": "payments",
    },
    {
        "code": "observability",
        "name": "Observability",
        "description": "Health, metrics, tracing",
        "api_base": "/metrics",
        "status": "production",
        "owner_team": "platform",
    },
    {
        "code": "rbac",
        "name": "RBAC",
        "description": "Enterprise role-based access control",
        "api_base": "/api/v1/enterprise/",
        "status": "production",
        "owner_team": "enterprise",
    },
    {
        "code": "abac",
        "name": "ABAC",
        "description": "Attribute policies via enterprise rules engine",
        "api_base": "/api/v1/enterprise/",
        "status": "production",
        "owner_team": "enterprise",
    },
    {
        "code": "workflow",
        "name": "Workflow Engine",
        "description": "Reusable approval and process workflows",
        "api_base": "/api/v1/enterprise/",
        "status": "production",
        "owner_team": "enterprise",
    },
]

DOMAINS = [
    {
        "code": "mobility",
        "name": "Mobility",
        "description": "Ride hailing, delivery, logistics, fleet, stations",
        "icon": "local_taxi",
        "route": "/mobility",
        "api_base": "/api/v1/trips/",
        "status": "active",
        "sort_order": 10,
        "required_services": ["identity", "payments", "wallet", "registry", "gis", "notifications", "audit"],
        "capabilities": ["ride_hailing", "delivery", "logistics", "fleet", "stations", "national_ops"],
    },
    {
        "code": "commerce",
        "name": "Taifa Commerce (MOS)",
        "description": "Merchant Operating System — catalog, inventory, POS, orders; money via enterprise capture; Winga publish optional",
        "icon": "storefront",
        "route": "/commerce",
        "api_base": "/api/v1/mos/",
        "status": "active",
        "sort_order": 20,
        "required_services": ["identity", "payments", "wallet", "notifications", "audit"],
        "capabilities": ["merchant", "inventory", "pos", "orders", "marketplace", "supplier", "procurement", "crm"],
    },
    {
        "code": "winga",
        "name": "Winga Brokerage",
        "description": "Universal brokerage — verified intermediaries connect customers with providers and earn commissions",
        "icon": "handshake",
        "route": "/winga",
        "api_base": "/api/v1/winga/",
        "status": "active",
        "sort_order": 21,
        "required_services": ["identity", "payments", "wallet", "ledger", "notifications", "audit", "ai"],
        "capabilities": [
            "brokerage",
            "leads",
            "quotations",
            "commissions",
            "bookings",
            "providers",
            "trust",
        ],
    },
    {
        "code": "healthcare",
        "name": "Healthcare",
        "description": "Hospitals, clinics, appointments, ambulances, telemedicine",
        "icon": "local_hospital",
        "route": "/health",
        "api_base": "/api/v1/commerce/",
        "status": "active",
        "sort_order": 30,
        "required_services": ["identity", "payments", "wallet", "notifications", "documents", "gis"],
        "capabilities": ["appointments", "ambulances", "telemedicine", "labs"],
    },
    {
        "code": "agriculture",
        "name": "Agriculture",
        "description": "Farm registry, produce marketplace, inputs, ag logistics",
        "icon": "agriculture",
        "route": "/agriculture",
        "api_base": "/api/v1/ecosystem/agriculture/",
        "status": "active",
        "sort_order": 40,
        "required_services": ["identity", "payments", "wallet", "gis", "notifications"],
        "capabilities": ["farm_registry", "produce_market", "equipment_rental", "input_market", "ag_logistics"],
    },
    {
        "code": "education",
        "name": "Education",
        "description": "Schools, universities, fees, attendance, student transport",
        "icon": "school",
        "route": "/education",
        "api_base": "/api/v1/commerce/",
        "status": "active",
        "sort_order": 50,
        "required_services": ["identity", "payments", "wallet", "notifications"],
        "capabilities": ["fees", "attendance", "learning", "student_transport"],
    },
    {
        "code": "government",
        "name": "Government",
        "description": "Licensing, permits, certificates, inspections, citizen services",
        "icon": "account_balance",
        "route": "/gov",
        "api_base": "/api/v1/commerce/",
        "status": "active",
        "sort_order": 60,
        "required_services": ["identity", "payments", "documents", "workflow", "audit", "reporting"],
        "capabilities": ["licensing", "permits", "certificates", "inspections", "citizen_services"],
    },
    {
        "code": "tourism",
        "name": "Tourism",
        "description": "Hotels, tours, packages, travel transport",
        "icon": "landscape",
        "route": "/tourism",
        "api_base": "/api/v1/commerce/",
        "status": "active",
        "sort_order": 70,
        "required_services": ["identity", "payments", "wallet", "gis", "notifications"],
        "capabilities": ["hotels", "tours", "packages", "reservations"],
    },
    {
        "code": "logistics",
        "name": "Logistics",
        "description": "Warehousing, freight, cargo, cross-border, tracking",
        "icon": "local_shipping",
        "route": "/jobs",
        "api_base": "/api/v1/trips/",
        "status": "active",
        "sort_order": 80,
        "required_services": ["identity", "payments", "gis", "notifications", "audit"],
        "capabilities": ["warehousing", "freight", "cargo", "tracking", "cross_border"],
    },
    {
        "code": "enterprise",
        "name": "Enterprise",
        "description": "HR, payroll, treasury, procurement, expense, fleet",
        "icon": "business",
        "route": "/menu",
        "api_base": "/api/v1/enterprise/",
        "status": "active",
        "sort_order": 90,
        "required_services": ["identity", "payments", "rbac", "workflow", "audit", "reporting"],
        "capabilities": ["hr", "payroll", "treasury", "procurement", "expense", "fleet"],
    },
]

MODULES = [
    # Core — always on, non-toggleable
    {"code": "home", "name": "Home", "route": "/home", "icon": "home", "default_enabled": True, "sort_order": 1, "category": "core", "domain_code": None},
    {"code": "wallet", "name": "Wallet", "route": "/wallet", "icon": "account_balance_wallet", "default_enabled": True, "sort_order": 2, "category": "core", "domain_code": None},
    {"code": "ai", "name": "AI Assistant", "route": "/ai", "icon": "auto_awesome", "default_enabled": True, "sort_order": 3, "category": "core", "domain_code": None},
    {"code": "notifications", "name": "Notifications", "route": "/notifications", "icon": "notifications", "default_enabled": True, "sort_order": 4, "category": "core", "domain_code": None},
    {"code": "settings", "name": "Settings", "route": "/settings", "icon": "settings", "default_enabled": True, "sort_order": 5, "category": "core", "domain_code": None},
    {"code": "profile", "name": "Profile", "route": "/profile", "icon": "person", "default_enabled": True, "sort_order": 6, "category": "core", "domain_code": None},
    # Mobility & transport
    {"code": "mobility", "name": "Mobility", "route": "/mobility", "icon": "local_taxi", "default_enabled": True, "sort_order": 10, "category": "service", "domain_code": "mobility"},
    {"code": "food", "name": "Food", "route": "/food", "icon": "restaurant", "default_enabled": True, "sort_order": 11, "category": "service", "domain_code": "mobility"},
    {"code": "express", "name": "Express", "route": "/express", "icon": "bolt", "default_enabled": True, "sort_order": 12, "category": "service", "domain_code": "commerce"},
    {"code": "driver", "name": "Driver", "route": "/driver", "icon": "directions_car", "default_enabled": False, "sort_order": 13, "category": "service", "domain_code": "mobility"},
    {"code": "mobility_driver", "name": "Mobility Driver", "route": "/mobility-driver", "icon": "two_wheeler", "default_enabled": False, "sort_order": 14, "category": "service", "domain_code": "mobility"},
    {"code": "mobility_registry", "name": "Mobility Registry", "route": "/mobility-registry", "icon": "verified_user", "default_enabled": False, "sort_order": 15, "category": "service", "domain_code": "mobility"},
    {"code": "flights", "name": "Flights", "route": "/flights", "icon": "flight", "default_enabled": False, "sort_order": 16, "category": "service", "domain_code": "tourism"},
    {"code": "jobs", "name": "Jobs & Logistics", "route": "/jobs", "icon": "work", "default_enabled": False, "sort_order": 17, "category": "service", "domain_code": "logistics"},
    # Commerce & pay
    {"code": "pay", "name": "Pay", "route": "/pay", "icon": "payments", "default_enabled": True, "sort_order": 20, "category": "service", "domain_code": "commerce"},
    {"code": "tap", "name": "Tap & Pay", "route": "/tap", "icon": "contactless", "default_enabled": False, "sort_order": 21, "category": "service", "domain_code": "commerce"},
    {"code": "map", "name": "Accept (MAP)", "route": "/map", "icon": "qr_code_2", "default_enabled": True, "sort_order": 22, "category": "service", "domain_code": "commerce"},
    {"code": "winga", "name": "Winga", "route": "/winga", "icon": "handshake", "default_enabled": True, "sort_order": 23, "category": "service", "domain_code": "winga"},
    {"code": "commerce", "name": "Commerce (MOS)", "route": "/commerce", "icon": "storefront", "default_enabled": True, "sort_order": 24, "category": "service", "domain_code": "commerce"},
    {"code": "merchant", "name": "Merchant", "route": "/merchant", "icon": "store", "default_enabled": False, "sort_order": 25, "category": "service", "domain_code": "commerce"},
    # Lifestyle & citizen
    {"code": "stays", "name": "Hotels", "route": "/stays", "icon": "hotel", "default_enabled": False, "sort_order": 30, "category": "service", "domain_code": "tourism"},
    {"code": "tourism", "name": "Tourism", "route": "/tourism", "icon": "landscape", "default_enabled": False, "sort_order": 31, "category": "service", "domain_code": "tourism"},
    {"code": "health", "name": "Health", "route": "/health", "icon": "local_hospital", "default_enabled": False, "sort_order": 32, "category": "service", "domain_code": "healthcare"},
    {"code": "education", "name": "Education", "route": "/education", "icon": "school", "default_enabled": False, "sort_order": 33, "category": "service", "domain_code": "education"},
    {"code": "agriculture", "name": "Agriculture", "route": "/agriculture", "icon": "agriculture", "default_enabled": False, "sort_order": 34, "category": "service", "domain_code": "agriculture"},
    {"code": "government", "name": "Government", "route": "/gov", "icon": "account_balance", "default_enabled": False, "sort_order": 35, "category": "service", "domain_code": "government"},
    {"code": "housing", "name": "Housing", "route": "/housing", "icon": "cottage", "default_enabled": False, "sort_order": 36, "category": "service", "domain_code": None},
    {"code": "wealth", "name": "Wealth", "route": "/wealth", "icon": "savings", "default_enabled": False, "sort_order": 37, "category": "service", "domain_code": None},
    {"code": "insurance", "name": "Insurance", "route": "/insurance", "icon": "health_and_safety", "default_enabled": False, "sort_order": 38, "category": "service", "domain_code": None},
    {"code": "family", "name": "Family", "route": "/family", "icon": "family_restroom", "default_enabled": False, "sort_order": 39, "category": "service", "domain_code": None},
    {"code": "huduma", "name": "Huduma", "route": "/huduma", "icon": "handyman", "default_enabled": False, "sort_order": 40, "category": "service", "domain_code": "government"},
    {"code": "chat", "name": "Chat", "route": "/chat", "icon": "chat_bubble", "default_enabled": False, "sort_order": 41, "category": "service", "domain_code": None},
    {"code": "nfc", "name": "NFC", "route": "/nfc", "icon": "nfc", "default_enabled": False, "sort_order": 42, "category": "service", "domain_code": None},
    {"code": "search", "name": "Search", "route": "/search", "icon": "search", "default_enabled": True, "sort_order": 43, "category": "service", "domain_code": None},
    # Operations consoles
    {"code": "station_ops", "name": "Station Ops", "route": "/station-ops", "icon": "store_mall_directory", "default_enabled": False, "sort_order": 80, "category": "ops", "domain_code": "mobility"},
    {"code": "city_ops", "name": "City Ops", "route": "/city-ops", "icon": "map", "default_enabled": False, "sort_order": 81, "category": "ops", "domain_code": "mobility"},
    {"code": "fleet_ops", "name": "Fleet Ops", "route": "/fleet-ops", "icon": "local_shipping", "default_enabled": False, "sort_order": 82, "category": "ops", "domain_code": "mobility"},
    {"code": "regional_ops", "name": "Regional Ops", "route": "/regional-ops", "icon": "account_balance", "default_enabled": False, "sort_order": 83, "category": "ops", "domain_code": None},
    {"code": "national_ops", "name": "National Ops", "route": "/national-ops", "icon": "public", "default_enabled": False, "sort_order": 84, "category": "ops", "domain_code": None},
    {"code": "ai_ops", "name": "AI Command Center", "route": "/ai-ops", "icon": "psychology", "default_enabled": False, "sort_order": 85, "category": "ops", "domain_code": None},
    {"code": "continental_ops", "name": "Continental Ops", "route": "/continental-ops", "icon": "public", "default_enabled": False, "sort_order": 86, "category": "ops", "domain_code": None},
    {"code": "registry_admin", "name": "Registry Admin", "route": "/mobility-registry/admin", "icon": "fact_check", "default_enabled": False, "sort_order": 87, "category": "ops", "domain_code": "mobility"},
    {"code": "admin", "name": "Platform Admin", "route": "/admin", "icon": "admin_panel_settings", "default_enabled": False, "sort_order": 88, "category": "ops", "domain_code": "enterprise"},
    {"code": "ops", "name": "Live Ops", "route": "/ops", "icon": "monitor_heart", "default_enabled": False, "sort_order": 89, "category": "ops", "domain_code": None},
]

WORKFLOW_BINDINGS = [
    {
        "code": "ride_approval",
        "name": "Ride Approval",
        "domain_code": "mobility",
        "workflow_definition_code": "ecosystem.ride_approval",
        "example_resource_type": "trip",
        "description": "Corporate / priority ride approval",
    },
    {
        "code": "merchant_approval",
        "name": "Merchant Approval",
        "domain_code": "commerce",
        "workflow_definition_code": "ecosystem.merchant_approval",
        "example_resource_type": "merchant",
        "description": "Merchant onboarding approval",
    },
    {
        "code": "hospital_registration",
        "name": "Hospital Registration",
        "domain_code": "healthcare",
        "workflow_definition_code": "ecosystem.hospital_registration",
        "example_resource_type": "facility",
        "description": "Healthcare facility registration",
    },
    {
        "code": "government_permit",
        "name": "Government Permit",
        "domain_code": "government",
        "workflow_definition_code": "ecosystem.government_permit",
        "example_resource_type": "permit",
        "description": "Citizen permit application",
    },
    {
        "code": "driver_verification",
        "name": "Driver Verification",
        "domain_code": "mobility",
        "workflow_definition_code": "ecosystem.driver_verification",
        "example_resource_type": "driver_application",
        "description": "Driver identity and license verification",
    },
    {
        "code": "business_verification",
        "name": "Business Verification",
        "domain_code": "enterprise",
        "workflow_definition_code": "ecosystem.business_verification",
        "example_resource_type": "partner",
        "description": "Partner / BRELA-linked business verification",
    },
]

AI_CAPABILITIES = [
    {"code": "recommendations", "name": "Recommendations", "description": "Cross-domain product and service recommendations"},
    {"code": "fraud_detection", "name": "Fraud Detection", "description": "Advisory fraud signals (risk engine remains authoritative)"},
    {"code": "demand_prediction", "name": "Demand Prediction", "description": "Mobility and commerce demand forecasts"},
    {"code": "voice_assistant", "name": "Voice Assistant", "description": "Natural language assistant"},
    {"code": "ocr", "name": "OCR", "description": "Document text extraction"},
    {"code": "route_optimization", "name": "Route Optimization", "description": "Multi-stop and fleet routing advice"},
    {"code": "risk_analysis", "name": "Risk Analysis", "description": "Credit and operational risk scoring advice"},
    {"code": "smart_search", "name": "Smart Search", "description": "Unified catalog and knowledge search"},
]
