# Generated by Django 5.1.6 on 2026-07-18 13:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('domain_code', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('capabilities', models.JSONField(default=list)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AiDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128)),
                ('domain_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('agent_code', models.CharField(blank=True, default='', max_length=64)),
                ('capability_code', models.CharField(db_index=True, max_length=64)),
                ('model_version', models.CharField(default='', max_length=64)),
                ('request_payload', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('confidence_e4', models.PositiveIntegerField(default=0)),
                ('reasoning_summary', models.TextField(blank=True, default='')),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('requires_human_approval', models.BooleanField(default=False)),
                ('approval_status', models.CharField(default='not_required', max_length=16)),
                ('workflow_instance_id', models.UUIDField(blank=True, null=True)),
                ('safety', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('domain_code', models.CharField(blank=True, default='', max_length=64)),
                ('trigger_event', models.CharField(max_length=64)),
                ('capability_code', models.CharField(max_length=64)),
                ('auto_apply', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('domain_code', models.CharField(blank=True, default='', max_length=64)),
                ('purpose', models.CharField(default='training', max_length=64)),
                ('schema_ref', models.CharField(blank=True, default='', max_length=255)),
                ('pii_class', models.CharField(default='none', max_length=16)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=96, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('domain_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('body', models.TextField()),
                ('source_uri', models.CharField(blank=True, default='', max_length=512)),
                ('citation', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(default='en', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRegistryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('modality', models.CharField(default='text', max_length=32)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('status', models.CharField(default='active', max_length=16)),
                ('adapter_path', models.CharField(default='ai_os.adapters.StubInferenceAdapter', max_length=255)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('deployment', models.CharField(default='hybrid', max_length=32)),
                ('rollback_to', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='completed', max_length=16)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='taifa_ai_os.aidecision')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='taifa_ai_os.automationrule')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStoreEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=128)),
                ('feature_set', models.CharField(db_index=True, max_length=64)),
                ('features', models.JSONField(default=dict)),
                ('as_of', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('model_version', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'feature_set', '-as_of'], name='taifa_ai_os_entity__e4f61e_idx')],
            },
        ),
        migrations.CreateModel(
            name='InferenceMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('capability_code', models.CharField(db_index=True, max_length=64)),
                ('domain_code', models.CharField(blank=True, default='', max_length=64)),
                ('invocations', models.PositiveBigIntegerField(default=0)),
                ('errors', models.PositiveBigIntegerField(default=0)),
                ('latency_sum_ms', models.PositiveBigIntegerField(default=0)),
                ('token_sum', models.PositiveBigIntegerField(default=0)),
                ('approval_pending', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'capability_code', 'domain_code'), name='taifa_ai_os_unique_daily_metric')],
            },
        ),
        migrations.CreateModel(
            name='CapabilityDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('family', models.CharField(db_index=True, max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('requires_human_approval', models.BooleanField(default=False)),
                ('approval_workflow_code', models.CharField(blank=True, default='', max_length=64)),
                ('pii_policy', models.CharField(default='redact', max_length=16)),
                ('status', models.CharField(default='available', max_length=16)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities', to='taifa_ai_os.modelregistryentry')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=32)),
                ('severity', models.CharField(default='medium', max_length=16)),
                ('principal', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_events', to='taifa_ai_os.aidecision')),
            ],
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('domain_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['collection', 'domain_code'], name='taifa_ai_os_collect_aa4c58_idx')],
            },
        ),
    ]
