# Generated by Django 5.1.6 on 2026-07-10 21:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('event_type', models.CharField(max_length=64)),
                ('provider_ref', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('result', models.CharField(blank=True, default='', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('user_wallet', 'User Wallet'), ('provider_settlement', 'Provider Settlement'), ('external_mobile_money', 'External Mobile Money'), ('external_bank', 'External Bank'), ('fee_income', 'Fee Income'), ('tax_payable', 'Tax Payable'), ('crypto_vault', 'Crypto Vault'), ('suspense', 'Suspense')], max_length=32)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('BTC', 'Bitcoin')], max_length=8)),
                ('owner', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['owner'], name='payments_le_owner_e32258_idx'), models.Index(fields=['account_type'], name='payments_le_account_117c63_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('send_money', 'Send Money'), ('receive_money', 'Receive Money'), ('bill_payment', 'Bill Payment'), ('top_up', 'Top Up'), ('withdrawal', 'Withdrawal'), ('merchant_payment', 'Merchant Payment'), ('refund', 'Refund'), ('ride_fare', 'Ride Fare')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=16)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('amount_minor', models.BigIntegerField()),
                ('fee_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('BTC', 'Bitcoin')], max_length=8)),
                ('counterparty', models.CharField(max_length=255)),
                ('method_kind', models.CharField(max_length=24)),
                ('method_label', models.CharField(blank=True, default='', max_length=128)),
                ('method_ref', models.CharField(blank=True, default='', max_length=128)),
                ('operator', models.CharField(blank=True, default='', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_ref', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_ref', to='payments.ledgerentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.transaction'),
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=32)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=8)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('BTC', 'Bitcoin')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='payments.ledgeraccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='payments.ledgerentry')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='payments_po_account_d53258_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='payments_tr_type_0525a2_idx'),
        ),
    ]
