# Generated by Django 5.1.6 on 2026-07-10 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_append_only_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', '-created_at'], name='payments_tr_owner_da004d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['owner'], name='payments_de_owner_adcb8a_idx'),
        ),
    ]
