# Generated by Django 5.1.6 on 2026-07-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_device_transaction_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('opening', 'Opening'), ('settle', 'Settle'), ('hold', 'Hold'), ('release', 'Release'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], db_index=True, default='settle', max_length=16),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='payments.ledgerentry'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('user_wallet', 'User Wallet'), ('funds_on_hold', 'Funds On Hold'), ('provider_settlement', 'Provider Settlement'), ('external_mobile_money', 'External Mobile Money'), ('external_bank', 'External Bank'), ('fee_income', 'Fee Income'), ('commission_income', 'Commission Income'), ('merchant_payable', 'Merchant Payable'), ('treasury', 'Treasury'), ('tax_payable', 'Tax Payable'), ('crypto_vault', 'Crypto Vault'), ('suspense', 'Suspense')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('send_money', 'Send Money'), ('receive_money', 'Receive Money'), ('bill_payment', 'Bill Payment'), ('top_up', 'Top Up'), ('withdrawal', 'Withdrawal'), ('merchant_payment', 'Merchant Payment'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('chargeback', 'Chargeback'), ('ride_fare', 'Ride Fare')], max_length=24),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['parent'], name='payments_tr_parent__345a27_idx'),
        ),
    ]
