# Generated by Django 5.1.6 on 2026-07-15 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_money_flows_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='base_amount_minor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='base_currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AddField(
            model_name='posting',
            name='fx_rate_e8',
            field=models.BigIntegerField(default=100000000),
        ),
        migrations.AlterField(
            model_name='ledgeraccount',
            name='account_type',
            field=models.CharField(choices=[('treasury', 'Treasury'), ('provider_settlement', 'Provider Settlement'), ('settlement_pending', 'Settlement Pending'), ('cash_in_transit', 'Cash In Transit'), ('wallet_clearing', 'Wallet Clearing'), ('external_mobile_money', 'External Mobile Money'), ('external_bank', 'External Bank'), ('crypto_vault', 'Crypto Vault'), ('user_wallet', 'User Wallet'), ('funds_on_hold', 'Funds On Hold'), ('merchant_payable', 'Merchant Payable'), ('tax_payable', 'Tax Payable'), ('provider_payable', 'Provider Payable'), ('fees_payable', 'Fees Payable'), ('fee_income', 'Fee Income'), ('commission_income', 'Commission Income'), ('fx_gain', 'Fx Gain'), ('fx_loss', 'Fx Loss'), ('chargeback_expense', 'Chargeback Expense'), ('fraud_loss', 'Fraud Loss'), ('chargeback_reserve', 'Chargeback Reserve'), ('liquidity_reserve', 'Liquidity Reserve'), ('suspense', 'Suspense'), ('unknown_credits', 'Unknown Credits'), ('unknown_debits', 'Unknown Debits')], max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='payments_au_actor_57ae81_idx'), models.Index(fields=['action'], name='payments_au_action_4dee70_idx')],
            },
        ),
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('payment.created', 'Payment Created'), ('payment.authorized', 'Payment Authorized'), ('payment.captured', 'Payment Captured'), ('payment.settled', 'Payment Settled'), ('payment.failed', 'Payment Failed'), ('payment.rejected', 'Payment Rejected'), ('payment.cancelled', 'Payment Cancelled'), ('withdrawal.requested', 'Withdrawal Requested'), ('withdrawal.approved', 'Withdrawal Approved'), ('withdrawal.completed', 'Withdrawal Completed'), ('withdrawal.rejected', 'Withdrawal Rejected'), ('refund.created', 'Refund Created'), ('refund.completed', 'Refund Completed'), ('reversal.completed', 'Reversal Completed'), ('risk.denied', 'Risk Denied'), ('risk.review', 'Risk Review')], db_index=True, max_length=64)),
                ('owner', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='domain_events', to='payments.transaction')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='payments_do_event_t_1a30ed_idx')],
            },
        ),
    ]
