# Generated by Django 5.1.6 on 2026-07-15 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_core_banking_control_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('reconciled', 'Reconciled'), ('failed', 'Failed')], default='received', max_length=16)),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('exception_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookReplayGuard',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('missing_settlement', 'Missing Settlement'), ('duplicate_settlement', 'Duplicate Settlement'), ('amount_mismatch', 'Amount Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('unexpected_settlement', 'Unexpected Settlement'), ('late_settlement', 'Late Settlement'), ('unknown_transaction', 'Unknown Transaction')], db_index=True, max_length=32)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=128)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_exceptions', to='payments.transaction')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='payments.settlementbatch')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_ref', models.CharField(db_index=True, max_length=128)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('BTC', 'Bitcoin')], max_length=8)),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=8)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('missing_internal', 'Missing Internal'), ('amount_mismatch', 'Amount Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('duplicate', 'Duplicate'), ('unexpected', 'Unexpected'), ('late', 'Late')], default='pending', max_length=24)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='payments.settlementbatch')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_lines', to='payments.transaction')),
            ],
        ),
    ]
