# Generated by Django 5.1.6 on 2026-07-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_p0_production_gates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainevent',
            name='event_type',
            field=models.CharField(choices=[('payment.created', 'Payment Created'), ('payment.authorized', 'Payment Authorized'), ('payment.captured', 'Payment Captured'), ('payment.settled', 'Payment Settled'), ('payment.failed', 'Payment Failed'), ('payment.rejected', 'Payment Rejected'), ('payment.cancelled', 'Payment Cancelled'), ('withdrawal.requested', 'Withdrawal Requested'), ('withdrawal.approved', 'Withdrawal Approved'), ('withdrawal.completed', 'Withdrawal Completed'), ('withdrawal.rejected', 'Withdrawal Rejected'), ('refund.created', 'Refund Created'), ('refund.completed', 'Refund Completed'), ('reversal.completed', 'Reversal Completed'), ('risk.denied', 'Risk Denied'), ('risk.review', 'Risk Review'), ('settlement.created', 'Settlement Created'), ('settlement.completed', 'Settlement Completed'), ('settlement.cancelled', 'Settlement Cancelled'), ('merchant.paid', 'Merchant Paid'), ('merchant.captured', 'Merchant Captured'), ('chargeback.opened', 'Chargeback Opened'), ('chargeback.evidence_requested', 'Chargeback Evidence Requested'), ('chargeback.evidence_submitted', 'Chargeback Evidence Submitted'), ('chargeback.representment', 'Chargeback Representment'), ('chargeback.won', 'Chargeback Won'), ('chargeback.lost', 'Chargeback Lost'), ('chargeback.reversed', 'Chargeback Reversed'), ('treasury.transfer', 'Treasury Transfer'), ('reserve.updated', 'Reserve Updated'), ('fee.collected', 'Fee Collected'), ('commission.calculated', 'Commission Calculated'), ('tax.posted', 'Tax Posted'), ('approval.requested', 'Approval Requested'), ('approval.granted', 'Approval Granted'), ('approval.denied', 'Approval Denied'), ('workflow.started', 'Workflow Started'), ('workflow.completed', 'Workflow Completed'), ('rule.evaluated', 'Rule Evaluated')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('opening', 'Opening'), ('settle', 'Settle'), ('hold', 'Hold'), ('release', 'Release'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment'), ('merchant_capture', 'Merchant Capture'), ('merchant_payout', 'Merchant Payout'), ('chargeback', 'Chargeback'), ('treasury', 'Treasury'), ('fee', 'Fee'), ('tax', 'Tax'), ('commission', 'Commission'), ('reserve', 'Reserve')], db_index=True, default='settle', max_length=16),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('send_money', 'Send Money'), ('receive_money', 'Receive Money'), ('bill_payment', 'Bill Payment'), ('top_up', 'Top Up'), ('withdrawal', 'Withdrawal'), ('merchant_payment', 'Merchant Payment'), ('refund', 'Refund'), ('reversal', 'Reversal'), ('chargeback', 'Chargeback'), ('ride_fare', 'Ride Fare'), ('treasury_transfer', 'Treasury Transfer'), ('merchant_settlement', 'Merchant Settlement'), ('fee_collection', 'Fee Collection'), ('tax_posting', 'Tax Posting')], max_length=32),
        ),
    ]
