# Generated by Django 5.2.11 on 2026-08-08 08:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_device_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='posting',
            name='base_currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='posting',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='settlementline',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=24, unique=True)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=16)),
                ('single_use', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('total_paid_minor', models.BigIntegerField(default=0)),
                ('payment_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='payments_pa_owner_6e92fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester', models.CharField(db_index=True, max_length=128)),
                ('payer', models.CharField(db_index=True, max_length=128)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_requests', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', '-created_at'], name='payments_mo_request_424ce8_idx'), models.Index(fields=['payer', 'status'], name='payments_mo_payer_a78c64_idx')],
            },
        ),
    ]
