# Generated by Django 5.2.11 on 2026-08-08 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_ledgeraccount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('contact_owner', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-favorite', 'display_name'],
                'indexes': [models.Index(fields=['owner', '-favorite'], name='payments_co_owner_4c633f_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'contact_owner'), name='unique_contact_per_owner')],
            },
        ),
    ]
