# Generated by Django 5.2.11 on 2026-08-08 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_device_phone_number_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organizer', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('total_amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organizer', '-created_at'], name='payments_bi_organiz_8d8452_idx')],
            },
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shares', to='payments.billsplit'),
        ),
    ]
