# Generated by Django 5.2.11 on 2026-08-08 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_billsplit_moneyrequest_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('payee', models.CharField(max_length=128)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('emoji', models.CharField(blank=True, default='', max_length=16)),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('max_consecutive_failures', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='payments_re_owner_032e6a_idx'), models.Index(fields=['status', 'next_run_at'], name='payments_re_status_355b9f_idx')],
            },
        ),
    ]
