# Generated by Django 5.2.11 on 2026-08-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_recurringpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='fee_bps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
