# Generated by Django 5.2.17 on 2026-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_pushnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingCap',
            fields=[
                ('owner', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=8)),
                ('limit_minor', models.BigIntegerField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
