# Generated by Django 5.1.6 on 2026-07-14 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('picking_up', 'Picking Up'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='confirmed', max_length=32)),
                ('restaurant_id', models.CharField(max_length=64)),
                ('restaurant_name', models.CharField(max_length=128)),
                ('subtotal_minor', models.BigIntegerField()),
                ('delivery_fee_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('courier_name', models.CharField(blank=True, default='', max_length=128)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
