# Generated by Django 5.1.6 on 2026-07-14 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='confirmed', max_length=32)),
                ('hotel_id', models.CharField(max_length=64)),
                ('hotel_name', models.CharField(max_length=128)),
                ('room_name', models.CharField(max_length=128)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('nights', models.PositiveSmallIntegerField(default=1)),
                ('nightly_rate_minor', models.BigIntegerField()),
                ('taxes_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=32)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
