# Generated by Django 5.1.6 on 2026-07-14 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_staybooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('held', 'Held'), ('ticketed', 'Ticketed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='ticketed', max_length=32)),
                ('airline', models.CharField(max_length=64)),
                ('flight_number', models.CharField(max_length=32)),
                ('origin_code', models.CharField(max_length=8)),
                ('destination_code', models.CharField(max_length=8)),
                ('depart_at', models.DateTimeField()),
                ('passengers', models.PositiveSmallIntegerField(default=1)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('pnr', models.CharField(blank=True, default='', max_length=32)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='confirmed', max_length=32)),
                ('tour_id', models.CharField(max_length=64)),
                ('tour_title', models.CharField(max_length=128)),
                ('experience_date', models.DateField()),
                ('guests', models.PositiveSmallIntegerField(default=2)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=32)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
