# Generated by Django 5.1.6 on 2026-07-15 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_flightbooking_tourbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='WingaOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('driver_assigned', 'Driver Assigned'), ('pickup', 'Pickup'), ('delivering', 'Delivering'), ('completed', 'Completed')], default='placed', max_length=32)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('item_count', models.PositiveSmallIntegerField(default=1)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('courier_name', models.CharField(blank=True, default='', max_length=128)),
                ('eta_label', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WingaServiceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('service_id', models.CharField(max_length=64)),
                ('service_title', models.CharField(max_length=128)),
                ('slot_label', models.CharField(max_length=64)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WingaShopApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(default='Retail', max_length=64)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
