# Generated by Django 5.1.6 on 2026-07-15 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_winga_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='in_review', max_length=32)),
                ('service_id', models.CharField(max_length=64)),
                ('service_title', models.CharField(max_length=128)),
                ('agency', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('applicant_name', models.CharField(max_length=128)),
                ('fee_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('eta_days', models.PositiveSmallIntegerField(default=7)),
                ('reference', models.CharField(blank=True, default='', max_length=32)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
