# Generated by Django 5.1.6 on 2026-07-15 15:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_gov_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='confirmed', max_length=32)),
                ('facility_id', models.CharField(max_length=64)),
                ('facility_name', models.CharField(max_length=128)),
                ('specialty', models.CharField(blank=True, default='', max_length=128)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('patient_name', models.CharField(max_length=128)),
                ('slot_at', models.DateTimeField()),
                ('fee_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=32)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
