# Generated by Django 5.1.6 on 2026-07-15 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_health_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='invoiced', max_length=32)),
                ('school_id', models.CharField(max_length=64)),
                ('school_name', models.CharField(max_length=128)),
                ('level', models.CharField(blank=True, default='', max_length=64)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('student_name', models.CharField(max_length=128)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=32)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HousingInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('scheduled', 'Scheduled'), ('deposit_paid', 'Deposit Paid'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('listing_id', models.CharField(max_length=64)),
                ('listing_title', models.CharField(max_length=128)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('beds', models.PositiveSmallIntegerField(default=1)),
                ('baths', models.PositiveSmallIntegerField(default=1)),
                ('monthly_rent_minor', models.BigIntegerField()),
                ('deposit_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('viewing_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
