# Generated by Django 5.1.6 on 2026-07-15 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_edu_housing'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid')], default='accepted', max_length=32)),
                ('job_id', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=128)),
                ('area', models.CharField(blank=True, default='', max_length=128)),
                ('kind', models.CharField(default='gig', max_length=32)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('pay_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WealthContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('paid', 'Paid')], default='paid', max_length=32)),
                ('circle_id', models.CharField(max_length=64)),
                ('circle_name', models.CharField(max_length=128)),
                ('purpose', models.CharField(blank=True, default='', max_length=255)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
