# Generated by Django 5.1.6 on 2026-07-15 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_wealth_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='paid', max_length=32)),
                ('member_id', models.CharField(max_length=64)),
                ('member_name', models.CharField(max_length=128)),
                ('member_role', models.CharField(blank=True, default='', max_length=64)),
                ('member_phone', models.CharField(blank=True, default='', max_length=32)),
                ('kind', models.CharField(default='send', max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HudumaBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='paid', max_length=32)),
                ('service_id', models.CharField(max_length=64)),
                ('service_title', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('slot_label', models.CharField(max_length=64)),
                ('price_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('plan_id', models.CharField(max_length=64)),
                ('plan_name', models.CharField(max_length=128)),
                ('provider', models.CharField(blank=True, default='', max_length=128)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('premium_minor', models.BigIntegerField()),
                ('coverage_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('policy_ref', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
