# Generated by Django 5.1.6 on 2026-07-15 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_insurance_family_huduma'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('in_trip', 'In Trip'), ('completed', 'Completed'), ('declined', 'Declined')], default='offered', max_length=32)),
                ('rider_name', models.CharField(max_length=128)),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('fare_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('eta_minutes', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=32)),
                ('customer_name', models.CharField(max_length=128)),
                ('items_label', models.CharField(max_length=255)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
