from django.urls import path

from . import views

urlpatterns = [
    path("categories", views.CategoryListView.as_view()),
    path("types", views.TypeListView.as_view()),
    path("owners/me", views.OwnerProfileView.as_view()),
    path("listings", views.ListingListCreateView.as_view()),
    path("listings/<uuid:listing_id>", views.ListingDetailView.as_view()),
    path("listings/<uuid:listing_id>/media", views.ListingMediaView.as_view()),
    path(
        "listings/<uuid:listing_id>/submit-verification",
        views.ListingSubmitVerificationView.as_view(),
    ),
    path("listings/<uuid:listing_id>/verify", views.ListingVerifyView.as_view()),
    path(
        "listings/<uuid:listing_id>/verification-history",
        views.ListingVerificationHistoryView.as_view(),
    ),
    path("map/pins", views.MapPinsView.as_view()),
    path("map/clusters", views.MapClustersView.as_view()),
    path("discovery/search", views.DiscoveryAdvancedSearchView.as_view()),
    path("discovery/ai-search", views.DiscoveryAiSearchView.as_view()),
    path("discovery/recommendations", views.DiscoveryRecommendationsView.as_view()),
    path("discovery/recently-viewed", views.DiscoveryRecentlyViewedView.as_view()),
    path("discovery/compare", views.DiscoveryCompareView.as_view()),
    path("listings/<uuid:listing_id>/intelligence", views.ListingIntelligenceView.as_view()),
    path("listings/<uuid:listing_id>/commute", views.ListingCommuteView.as_view()),
    path("listings/<uuid:listing_id>/visit-score", views.ListingVisitScoreView.as_view()),
    path("listings/<uuid:listing_id>/experience", views.ListingExperienceView.as_view()),
    path("listings/<uuid:listing_id>/live-sessions", views.ListingLiveSessionListCreateView.as_view()),
    path("viewing-pass/plans", views.ViewingPassPlansView.as_view()),
    path("viewing-pass", views.ViewingPassListCreateView.as_view()),
    path("viewing-pass/verify", views.ViewingPassVerifyView.as_view()),
    path("viewing-pass/<uuid:pass_id>/pay", views.ViewingPassPayView.as_view()),
    path("viewing-pass/unlock/<uuid:listing_id>", views.ViewingPassUnlockListingView.as_view()),
    path("live-sessions/<uuid:session_id>", views.LiveSessionDetailView.as_view()),
    path("live-sessions/<uuid:session_id>/start", views.LiveSessionStartView.as_view()),
    path("live-sessions/<uuid:session_id>/join", views.LiveSessionJoinView.as_view()),
    path("live-sessions/<uuid:session_id>/end", views.LiveSessionEndView.as_view()),
    path("live-sessions/<uuid:session_id>/messages", views.LiveSessionMessagesView.as_view()),
    path("copilot/chat", views.CopilotChatView.as_view()),
    path("copilot/rankings", views.CopilotRankingsView.as_view()),
    path("listings/<uuid:listing_id>/negotiation-assist", views.ListingNegotiationAssistView.as_view()),
    path("listings/<uuid:listing_id>/relocation-assist", views.ListingRelocationAssistView.as_view()),
    path("listings/<uuid:listing_id>/assign-winga", views.ListingAssignWingaView.as_view()),
    path("wingas", views.PropertyWingaListView.as_view()),
    path("wingas/leaderboard", views.PropertyWingaLeaderboardView.as_view()),
    path("assignments", views.AssignmentListView.as_view()),
    path("assignments/<uuid:assignment_id>", views.AssignmentDetailView.as_view()),
    path("assignments/<uuid:assignment_id>/documents", views.AssignmentDocumentsView.as_view()),
    path("assignments/<uuid:assignment_id>/appointments", views.AssignmentAppointmentsView.as_view()),
    path("assignments/<uuid:assignment_id>/chat", views.AssignmentChatView.as_view()),
    path("assignments/<uuid:assignment_id>/commission-preview", views.AssignmentCommissionPreviewView.as_view()),
    path("listings/<uuid:listing_id>/applications", views.ListingApplicationCreateView.as_view()),
    path("applications", views.ApplicationListView.as_view()),
    path("applications/<uuid:application_id>", views.ApplicationDetailView.as_view()),
    path("applications/<uuid:application_id>/submit", views.ApplicationSubmitView.as_view()),
    path("applications/<uuid:application_id>/documents", views.ApplicationDocumentsView.as_view()),
    path("applications/<uuid:application_id>/verify-identity", views.ApplicationVerifyIdentityView.as_view()),
    path("applications/<uuid:application_id>/verify-income", views.ApplicationVerifyIncomeView.as_view()),
    path("applications/<uuid:application_id>/approve", views.ApplicationApproveView.as_view()),
    path("applications/<uuid:application_id>/generate-lease", views.ApplicationGenerateLeaseView.as_view()),
    path("leases/<uuid:lease_id>", views.LeaseDetailView.as_view()),
    path("leases/<uuid:lease_id>/sign", views.LeaseSignView.as_view()),
    path("leases/<uuid:lease_id>/renew", views.LeaseRenewView.as_view()),
    path("leases/<uuid:lease_id>/move", views.LeaseMoveWorkflowView.as_view()),
    path("lease-payments/<uuid:payment_id>/pay", views.LeasePaymentPayView.as_view()),
    path("move-workflows/<uuid:workflow_id>/complete", views.MoveWorkflowCompleteView.as_view()),
    path("ops/dashboard", views.OpsDashboardView.as_view()),
    path("ops/console", views.OpsConsoleView.as_view()),
    path("ops/analytics", views.OpsAnalyticsView.as_view()),
    path("ops/moderation-queue", views.OpsModerationQueueView.as_view()),
    path("ops/disputes", views.DisputeListCreateView.as_view()),
    path("ops/disputes/<uuid:dispute_id>/assign", views.DisputeAssignView.as_view()),
    path("ops/disputes/<uuid:dispute_id>/resolve", views.DisputeResolveView.as_view()),
    path("ops/listings/<uuid:listing_id>/suspend", views.OpsListingSuspendView.as_view()),
    path("ops/moderation/<uuid:report_id>/resolve", views.ModerationResolveView.as_view()),
    path("listings/<uuid:listing_id>/report", views.ListingReportView.as_view()),
    path("listings/<uuid:listing_id>/fraud-signals", views.ListingFraudSignalsView.as_view()),
    path("applications/<uuid:application_id>/fraud-signals", views.ApplicationFraudSignalsView.as_view()),
    path("favorites", views.FavoriteListCreateView.as_view()),
    path("saved-searches", views.SavedSearchListCreateView.as_view()),
]
