# Generated by Django 5.1.6 on 2026-07-17 17:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def seed_registry_configuration(apps, schema_editor):
    CompliancePolicy = apps.get_model("mobility_registry", "CompliancePolicy")
    PlatformRole = apps.get_model("enterprise", "PlatformRole")
    policies = {
        "driver": {
            "required_document_kinds": [
                "national_id",
                "driving_license",
                "passport_photo",
                "selfie_verification",
                "vehicle_permit",
                "good_conduct",
            ],
            "expiry_required_kinds": ["driving_license", "vehicle_permit", "good_conduct"],
        },
        "vehicle": {
            "required_document_kinds": [
                "vehicle_registration_card",
                "road_license",
                "insurance",
                "inspection_certificate",
                "ownership_certificate",
            ],
            "expiry_required_kinds": ["road_license", "insurance", "inspection_certificate"],
        },
        "station": {
            "required_document_kinds": [
                "local_government_approval",
                "station_registration",
                "leader_identification",
                "station_photo",
            ],
            "expiry_required_kinds": ["local_government_approval", "station_registration"],
        },
        "fleet": {
            "required_document_kinds": ["business_license", "owner_identification"],
            "expiry_required_kinds": ["business_license"],
        },
        "transport_company": {
            "required_document_kinds": [
                "brela_certificate",
                "tin_certificate",
                "business_license",
                "owner_identification",
            ],
            "expiry_required_kinds": ["business_license"],
        },
    }
    for app_type, values in policies.items():
        CompliancePolicy.objects.get_or_create(
            code=f"tz-{app_type}-v1",
            defaults={
                "application_type": app_type,
                **values,
                "reminder_days": [30, 14, 7, 1, 0],
                "suspend_on_expiry": True,
                "active": True,
                "version": 1,
            },
        )
    roles = {
        "customer": [],
        "driver": [],
        "station-manager": ["mobility_registry.station.manage"],
        "fleet-owner": ["mobility_registry.fleet.manage"],
        "regional-officer": [
            "mobility_registry.application.read",
            "mobility_registry.application.review",
            "mobility_registry.document.read",
            "mobility_registry.document.review",
            "mobility_registry.search",
            "mobility_registry.external.verify",
        ],
        "compliance-officer": [
            "mobility_registry.application.read",
            "mobility_registry.application.review",
            "mobility_registry.application.approve",
            "mobility_registry.application.reject",
            "mobility_registry.application.suspend",
            "mobility_registry.document.read",
            "mobility_registry.document.review",
            "mobility_registry.compliance.read",
            "mobility_registry.search",
            "mobility_registry.external.verify",
        ],
        "operations-officer": [
            "mobility_registry.application.read",
            "mobility_registry.compliance.read",
            "mobility_registry.search",
        ],
        "super-administrator": ["*"],
    }
    for code, permissions in roles.items():
        role, _ = PlatformRole.objects.get_or_create(
            code=code,
            defaults={"name": code.replace("-", " ").title()},
        )
        role.permissions = permissions
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_phase3_financial_platform'),
        ('trips', '0006_national_mobility_registry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(max_length=16)),
                ('status', models.CharField(db_index=True, default='open', max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('application_type', models.CharField(choices=[('driver', 'Driver'), ('vehicle', 'Vehicle'), ('station', 'Station'), ('fleet', 'Fleet'), ('transport_company', 'Transport Company')], max_length=32)),
                ('required_document_kinds', models.JSONField(default=list)),
                ('expiry_required_kinds', models.JSONField(default=list)),
                ('reminder_days', models.JSONField(default=list)),
                ('suspend_on_expiry', models.BooleanField(default=True)),
                ('police_clearance_required', models.BooleanField(default=False)),
                ('medical_certificate_required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('application_type', models.CharField(choices=[('driver', 'Driver'), ('vehicle', 'Vehicle'), ('station', 'Station'), ('fleet', 'Fleet'), ('transport_company', 'Transport Company')], db_index=True, max_length=32)),
                ('applicant_principal', models.CharField(db_index=True, max_length=128)),
                ('client_reference', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_review', 'Pending Review'), ('documents_missing', 'Documents Missing'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('approved', 'Approved'), ('blocked', 'Blocked')], db_index=True, default='draft', max_length=24)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('document_validation', 'Document Validation'), ('identity_validation', 'Identity Validation'), ('vehicle_validation', 'Vehicle Validation'), ('station_validation', 'Station Validation'), ('compliance_review', 'Compliance Review'), ('approval', 'Approval'), ('complete', 'Complete')], db_index=True, default='draft', max_length=32)),
                ('region', models.CharField(db_index=True, max_length=128)),
                ('district', models.CharField(db_index=True, max_length=128)),
                ('assigned_reviewer', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('approval_reference', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('operational_object_id', models.UUIDField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('check_type', models.CharField(max_length=64)),
                ('request_reference', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('requested_by', models.CharField(max_length=128)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('current', models.BooleanField(db_index=True, default=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('encrypted_payload', models.BinaryField()),
                ('encryption_nonce', models.BinaryField(max_length=12)),
                ('encryption_key_version', models.CharField(max_length=32)),
                ('document_number_ciphertext', models.BinaryField(blank=True, null=True)),
                ('document_number_nonce', models.BinaryField(blank=True, max_length=12, null=True)),
                ('document_number_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('document_number_masked', models.CharField(blank=True, default='', max_length=32)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=16)),
                ('reviewer', models.CharField(blank=True, default='', max_length=128)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=500)),
                ('uploaded_by', models.CharField(max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistryNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_principal', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('deduplication_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('from_stage', models.CharField(max_length=32)),
                ('to_stage', models.CharField(max_length=32)),
                ('actor', models.CharField(db_index=True, max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('comments', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier_type', models.CharField(max_length=32)),
                ('identifier_hash', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('identifier_type', 'identifier_hash'), name='registry_unique_active_blacklist')],
            },
        ),
        migrations.CreateModel(
            name='DriverRegistration',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver', serialize=False, to='mobility_registry.registryapplication')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('pii_key_version', models.CharField(max_length=32)),
                ('national_id_ciphertext', models.BinaryField()),
                ('national_id_nonce', models.BinaryField(max_length=12)),
                ('national_id_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('national_id_masked', models.CharField(max_length=32)),
                ('passport_ciphertext', models.BinaryField(blank=True, null=True)),
                ('passport_nonce', models.BinaryField(blank=True, max_length=12, null=True)),
                ('passport_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('phone_ciphertext', models.BinaryField()),
                ('phone_nonce', models.BinaryField(max_length=12)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('phone_masked', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gender', models.CharField(max_length=24)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(default='Tanzanian', max_length=64)),
                ('ward', models.CharField(blank=True, default='', max_length=128)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('postal_address', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_name', models.CharField(max_length=128)),
                ('emergency_phone_ciphertext', models.BinaryField()),
                ('emergency_phone_nonce', models.BinaryField(max_length=12)),
                ('emergency_phone_masked', models.CharField(max_length=32)),
                ('preferred_language', models.CharField(default='sw', max_length=16)),
                ('bank_account_ciphertext', models.BinaryField(blank=True, null=True)),
                ('bank_account_nonce', models.BinaryField(blank=True, max_length=12, null=True)),
                ('wallet_account_ref', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='FleetRegistration',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='fleet', serialize=False, to='mobility_registry.registryapplication')),
                ('pii_key_version', models.CharField(max_length=32)),
                ('fleet_type', models.CharField(max_length=24)),
                ('business_name', models.CharField(db_index=True, max_length=255)),
                ('brela_number_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('brela_number_ciphertext', models.BinaryField(blank=True, null=True)),
                ('brela_number_nonce', models.BinaryField(blank=True, max_length=12, null=True)),
                ('tin_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('tin_ciphertext', models.BinaryField(blank=True, null=True)),
                ('tin_nonce', models.BinaryField(blank=True, max_length=12, null=True)),
                ('business_license_number', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('declared_fleet_size', models.PositiveIntegerField(default=1)),
                ('bank_details_ciphertext', models.BinaryField(blank=True, null=True)),
                ('bank_details_nonce', models.BinaryField(blank=True, max_length=12, null=True)),
                ('settlement_wallet_ref', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StationRegistration',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='station', serialize=False, to='mobility_registry.registryapplication')),
                ('pii_key_version', models.CharField(max_length=32)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ward', models.CharField(blank=True, default='', max_length=128)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('manager_principal', models.CharField(db_index=True, max_length=128)),
                ('phone_ciphertext', models.BinaryField()),
                ('phone_nonce', models.BinaryField(max_length=12)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('phone_masked', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('operating_hours', models.JSONField(default=dict)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicle', serialize=False, to='mobility_registry.registryapplication')),
                ('pii_key_version', models.CharField(max_length=32)),
                ('mode', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bajaji', 'Bajaji'), ('taxi', 'Taxi'), ('private_car', 'Private Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck'), ('bus', 'Bus'), ('electric_vehicle', 'Electric Vehicle')], max_length=24)),
                ('registration_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('registration_number_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('chassis_number_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('chassis_number_ciphertext', models.BinaryField()),
                ('chassis_number_nonce', models.BinaryField(max_length=12)),
                ('engine_number_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('engine_number_ciphertext', models.BinaryField()),
                ('engine_number_nonce', models.BinaryField(max_length=12)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('year', models.PositiveSmallIntegerField()),
                ('fuel_type', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
            ],
        ),
        migrations.AddIndex(
            model_name='registryapplication',
            index=models.Index(fields=['application_type', 'status', 'created_at'], name='mobility_re_applica_eb62df_idx'),
        ),
        migrations.AddIndex(
            model_name='registryapplication',
            index=models.Index(fields=['region', 'district', 'status'], name='mobility_re_region_7b3a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='registryapplication',
            index=models.Index(fields=['assigned_reviewer', 'status'], name='mobility_re_assigne_a96218_idx'),
        ),
        migrations.AddConstraint(
            model_name='registryapplication',
            constraint=models.UniqueConstraint(fields=('applicant_principal', 'client_reference'), name='registry_unique_client_submission'),
        ),
        migrations.AddField(
            model_name='compliancefinding',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_findings', to='mobility_registry.registryapplication'),
        ),
        migrations.AddField(
            model_name='externalverificationrequest',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_checks', to='mobility_registry.registryapplication'),
        ),
        migrations.AddField(
            model_name='registrydocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='mobility_registry.registryapplication'),
        ),
        migrations.AddField(
            model_name='registrynotification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobility_registry.registryapplication'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='mobility_registry.registryapplication'),
        ),
        migrations.AddField(
            model_name='driverregistration',
            name='preferred_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_applicants', to='trips.station'),
        ),
        migrations.AddConstraint(
            model_name='stationregistration',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='registry_station_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='stationregistration',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='registry_station_valid_longitude'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='assigned_driver_application',
            field=models.ForeignKey(blank=True, limit_choices_to={'application_type': 'driver'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_vehicle_applications', to='mobility_registry.registryapplication'),
        ),
        migrations.AddConstraint(
            model_name='compliancefinding',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('application', 'code'), name='registry_unique_open_finding'),
        ),
        migrations.AddIndex(
            model_name='registrydocument',
            index=models.Index(fields=['application', 'status'], name='mobility_re_applica_9707c6_idx'),
        ),
        migrations.AddIndex(
            model_name='registrydocument',
            index=models.Index(fields=['expiry_date', 'status'], name='mobility_re_expiry__2c2594_idx'),
        ),
        migrations.AddConstraint(
            model_name='registrydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('current', True)), fields=('application', 'kind'), name='registry_one_current_document_kind'),
        ),
        migrations.RunPython(seed_registry_configuration, migrations.RunPython.noop),
    ]
