from django.urls import path

from . import city_views, national_views, passenger_views, transit_views, views

app_name = "trips"

urlpatterns = [
    path("", views.TripListCreateView.as_view(), name="list-create"),
    path("<uuid:trip_id>", views.TripDetailView.as_view(), name="detail"),
    path("<uuid:trip_id>/payment", views.TripPaymentView.as_view(), name="payment"),
    path("stations", views.StationListCreateView.as_view(), name="stations"),
    path("stations/nearby", views.NearbyStationView.as_view(), name="nearby-station"),
    path(
        "stations/rankings",
        city_views.StationRankingsView.as_view(),
        name="station-rankings",
    ),
    path(
        "stations/<uuid:station_id>/queue",
        views.StationQueueView.as_view(),
        name="station-queue",
    ),
    path(
        "stations/<uuid:station_id>/queue/join",
        views.StationQueueView.as_view(),
        name="station-queue-join",
    ),
    path(
        "stations/<uuid:station_id>/queue/leave",
        views.StationQueueLeaveView.as_view(),
        name="station-queue-leave",
    ),
    path(
        "stations/<uuid:station_id>/queue/reorder",
        views.StationQueueReorderView.as_view(),
        name="station-queue-reorder",
    ),
    path(
        "stations/<uuid:station_id>/intelligence",
        city_views.StationIntelligenceView.as_view(),
        name="station-intelligence",
    ),
    path(
        "stations/<uuid:station_id>/dashboard",
        views.StationDashboardView.as_view(),
        name="station-dashboard",
    ),
    path("fleets", views.FleetListCreateView.as_view(), name="fleets"),
    path(
        "fleets/<uuid:fleet_id>/dashboard",
        views.FleetDashboardView.as_view(),
        name="fleet-dashboard",
    ),
    path(
        "fleets/<uuid:fleet_id>/intelligence",
        city_views.FleetIntelligenceView.as_view(),
        name="fleet-intelligence",
    ),
    path("driver/profile", views.DriverProfileView.as_view(), name="driver-profile"),
    path(
        "verification/decisions",
        views.VerificationDecisionView.as_view(),
        name="verification-decisions",
    ),
    path("driver/earnings", views.DriverEarningsView.as_view(), name="driver-earnings"),
    path(
        "driver/performance",
        city_views.DriverPerformanceSelfView.as_view(),
        name="driver-performance-self",
    ),
    path(
        "driver/performance/<uuid:driver_id>",
        city_views.DriverPerformanceDetailView.as_view(),
        name="driver-performance",
    ),
    path(
        "drivers/rankings",
        city_views.DriverCityRankingsView.as_view(),
        name="driver-rankings",
    ),
    path(
        "driver/availability",
        views.DriverAvailabilityView.as_view(),
        name="driver-availability",
    ),
    path("driver/vehicles", views.VehicleListCreateView.as_view(), name="driver-vehicles"),
    path(
        "driver/vehicles/<uuid:vehicle_id>/logs",
        views.VehicleOperationalLogView.as_view(),
        name="vehicle-logs",
    ),
    path("driver/locations", views.DriverLocationBatchView.as_view(), name="driver-locations"),
    path("driver/offers", views.DriverOfferListView.as_view(), name="driver-offers"),
    path(
        "driver/offers/<uuid:offer_id>/accept",
        views.DriverOfferAcceptView.as_view(),
        name="driver-offer-accept",
    ),
    path(
        "driver/offers/<uuid:offer_id>/reject",
        views.DriverOfferRejectView.as_view(),
        name="driver-offer-reject",
    ),
    path("saved-locations", views.SavedLocationView.as_view(), name="saved-locations"),
    path("ratings", views.RatingCreateView.as_view(), name="ratings"),
    path("safety/incidents", views.SafetyIncidentView.as_view(), name="safety-incidents-create"),
    path(
        "safety/incidents/list",
        city_views.SafetyIncidentListView.as_view(),
        name="safety-incidents-list",
    ),
    path(
        "safety/incidents/<uuid:incident_id>",
        city_views.SafetyIncidentDetailView.as_view(),
        name="safety-incident-detail",
    ),
    path("notifications", views.MobilityNotificationListView.as_view(), name="notifications"),
    path("deliveries", views.DeliveryCreateView.as_view(), name="deliveries"),
    path(
        "deliveries/<uuid:delivery_id>/proof",
        views.DeliveryProofView.as_view(),
        name="delivery-proof",
    ),
    path("pricing/rules", views.PricingRuleView.as_view(), name="pricing-rules"),
    path("operations/dashboard", views.OperationsDashboardView.as_view(), name="ops-dashboard"),
    path("city/map", city_views.CityMapView.as_view(), name="city-map"),
    path("city/operations", city_views.CityOperationsView.as_view(), name="city-operations"),
    path("city/analytics", city_views.CityAnalyticsView.as_view(), name="city-analytics"),
    path(
        "regulatory/reports",
        views.RegulatoryReportView.as_view(),
        name="regulatory-reports",
    ),
    path(
        "intelligence/<str:kind>",
        views.MobilityIntelligenceView.as_view(),
        name="mobility-intelligence",
    ),
    path("favorites", passenger_views.FavoriteListCreateView.as_view(), name="favorites"),
    path(
        "favorites/<uuid:favorite_id>",
        passenger_views.FavoriteDeleteView.as_view(),
        name="favorite-delete",
    ),
    path(
        "recurring-rides",
        passenger_views.RecurringRidePlanView.as_view(),
        name="recurring-rides",
    ),
    path("accounts", passenger_views.MobilityAccountView.as_view(), name="accounts"),
    path(
        "shared-rides",
        passenger_views.SharedRideCreateView.as_view(),
        name="shared-rides",
    ),
    path("deliveries/list", passenger_views.DeliveryListView.as_view(), name="deliveries-list"),
    path(
        "fleets/<uuid:fleet_id>/drivers",
        passenger_views.FleetDriversView.as_view(),
        name="fleet-drivers",
    ),
    path(
        "fleets/<uuid:fleet_id>/vehicles",
        passenger_views.FleetVehiclesView.as_view(),
        name="fleet-vehicles",
    ),
    path(
        "fleets/<uuid:fleet_id>/schedules",
        passenger_views.FleetScheduleView.as_view(),
        name="fleet-schedules",
    ),
    path(
        "fleets/<uuid:fleet_id>/fuel",
        passenger_views.FleetFuelView.as_view(),
        name="fleet-fuel",
    ),
    path(
        "fleets/<uuid:fleet_id>/settlements",
        passenger_views.FleetSettlementsView.as_view(),
        name="fleet-settlements",
    ),
    path(
        "regional/supervisor",
        passenger_views.RegionalSupervisorDashboardView.as_view(),
        name="regional-supervisor",
    ),
    path("zones", passenger_views.MobilityZoneView.as_view(), name="zones"),
    path(
        "national/command-center",
        national_views.NationalCommandCenterView.as_view(),
        name="national-command-center",
    ),
    path("national/map", national_views.NationalMapView.as_view(), name="national-map"),
    path(
        "national/analytics",
        national_views.NationalAnalyticsView.as_view(),
        name="national-analytics",
    ),
    path(
        "national/optimization",
        national_views.NationalOptimizationView.as_view(),
        name="national-optimization",
    ),
    path(
        "national/reports",
        national_views.NationalReportView.as_view(),
        name="national-reports",
    ),
    path(
        "intercity/corridors",
        national_views.IntercityCorridorView.as_view(),
        name="intercity-corridors",
    ),
    path(
        "intercity/departures",
        national_views.IntercityDepartureView.as_view(),
        name="intercity-departures",
    ),
    path(
        "intercity/departures/<uuid:departure_id>/book",
        national_views.IntercityBookView.as_view(),
        name="intercity-book",
    ),
    path(
        "public-transit/routes",
        national_views.PublicTransitRouteView.as_view(),
        name="public-transit-routes",
    ),
    path(
        "public-transit/tickets",
        national_views.TransitTicketIssueView.as_view(),
        name="public-transit-tickets",
    ),
    path(
        "public-transit/tickets/validate",
        national_views.TransitTicketValidateView.as_view(),
        name="public-transit-validate",
    ),
    path(
        "enterprise/organizations",
        national_views.EnterpriseOrganizationView.as_view(),
        name="enterprise-orgs",
    ),
    path(
        "enterprise/organizations/<uuid:org_id>/employees",
        national_views.EnterpriseEmployeeView.as_view(),
        name="enterprise-employees",
    ),
    path(
        "enterprise/trips",
        national_views.EnterpriseTripView.as_view(),
        name="enterprise-trips",
    ),
    path(
        "emergency/dispatch",
        national_views.EmergencyDispatchView.as_view(),
        name="emergency-dispatch",
    ),
    path(
        "logistics/shipments",
        national_views.LogisticsShipmentView.as_view(),
        name="logistics-shipments",
    ),
    path(
        "open/partners",
        national_views.PartnerCredentialView.as_view(),
        name="open-partners",
    ),
    path(
        "open/catalog",
        national_views.PartnerCatalogView.as_view(),
        name="open-catalog",
    ),
    path("transit/home", transit_views.TransitHomeView.as_view(), name="transit-home"),
    path("transit/modes", transit_views.TransitModesView.as_view(), name="transit-modes"),
    path("transit/routes", transit_views.TransitRouteListView.as_view(), name="transit-routes"),
    path(
        "transit/routes/<uuid:route_id>",
        transit_views.TransitRouteDetailView.as_view(),
        name="transit-route-detail",
    ),
    path(
        "transit/stations/nearby",
        transit_views.TransitNearbyStationsView.as_view(),
        name="transit-stations-nearby",
    ),
    path(
        "transit/stations/<slug:stop_code>",
        transit_views.TransitStationDetailView.as_view(),
        name="transit-station-detail",
    ),
    path("transit/search", transit_views.TransitSearchView.as_view(), name="transit-search"),
    path(
        "transit/tickets/purchase",
        transit_views.TransitTicketPurchaseView.as_view(),
        name="transit-tickets-purchase",
    ),
    path(
        "transit/tickets/mine",
        transit_views.TransitMyTicketsView.as_view(),
        name="transit-tickets-mine",
    ),
    path(
        "transit/tickets/validate",
        transit_views.TransitTicketValidateView.as_view(),
        name="transit-tickets-validate",
    ),
    path(
        "transit/products",
        transit_views.TransitProductListView.as_view(),
        name="transit-products",
    ),
    path("transit/plan", transit_views.TransitPlanView.as_view(), name="transit-plan"),
    path(
        "transit/driver/runs",
        transit_views.TransitDriverRunListView.as_view(),
        name="transit-driver-runs",
    ),
    path(
        "transit/driver/runs/<uuid:run_id>",
        transit_views.TransitDriverRunUpdateView.as_view(),
        name="transit-driver-run-update",
    ),
    path("transit/map", transit_views.TransitLiveMapView.as_view(), name="transit-live-map"),
    path("transit/avl/ping", transit_views.TransitAvlPingView.as_view(), name="transit-avl-ping"),
    path("transit/profile", transit_views.TransitProfileView.as_view(), name="transit-profile"),
    path("transit/favorites", transit_views.TransitFavoriteListView.as_view(), name="transit-favorites"),
    path(
        "transit/favorites/<uuid:favorite_id>",
        transit_views.TransitFavoriteDeleteView.as_view(),
        name="transit-favorite-delete",
    ),
    path(
        "transit/notifications",
        transit_views.TransitNotificationListView.as_view(),
        name="transit-notifications",
    ),
    path("transit/feedback", transit_views.TransitFeedbackView.as_view(), name="transit-feedback"),
    path("transit/safety/sos", transit_views.TransitSafetySosView.as_view(), name="transit-safety-sos"),
    path("transit/analytics", transit_views.TransitAnalyticsView.as_view(), name="transit-analytics"),
    path("transit/admin/routes", transit_views.TransitAdminRouteView.as_view(), name="transit-admin-routes"),
    path(
        "transit/admin/routes/<uuid:route_id>",
        transit_views.TransitAdminRouteView.as_view(),
        name="transit-admin-route-update",
    ),
    path("transit/admin/products", transit_views.TransitAdminProductView.as_view(), name="transit-admin-products"),
    path(
        "transit/admin/products/<uuid:product_id>",
        transit_views.TransitAdminProductView.as_view(),
        name="transit-admin-product-update",
    ),
    path("transit/assistant", transit_views.TransitAssistantView.as_view(), name="transit-assistant"),
    path("transit/family", transit_views.TransitFamilyBundleView.as_view(), name="transit-family"),
    path("transit/family/members", transit_views.TransitFamilyMemberListView.as_view(), name="transit-family-members"),
    path(
        "transit/family/members/<uuid:member_id>",
        transit_views.TransitFamilyMemberDeleteView.as_view(),
        name="transit-family-member-delete",
    ),
    path("transit/lost-found", transit_views.TransitLostFoundView.as_view(), name="transit-lost-found"),
    path(
        "transit/lost-found/<uuid:item_id>/claim",
        transit_views.TransitLostFoundClaimView.as_view(),
        name="transit-lost-found-claim",
    ),
    path(
        "transit/lost-found/<uuid:item_id>/resolve",
        transit_views.TransitLostFoundResolveView.as_view(),
        name="transit-lost-found-resolve",
    ),
    path(
        "transit/lost-found/photo",
        transit_views.TransitLostFoundPhotoView.as_view(),
        name="transit-lost-found-photo",
    ),
    path(
        "transit/admin/lost-found",
        transit_views.TransitAdminLostFoundView.as_view(),
        name="transit-admin-lost-found",
    ),
    path(
        "transit/admin/lost-found/<uuid:item_id>/resolve",
        transit_views.TransitAdminLostFoundResolveView.as_view(),
        name="transit-admin-lost-found-resolve",
    ),
]
