# Generated by Django 5.1.6 on 2026-08-04 21:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourismItineraryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, default='', max_length=280)),
                ('days', models.JSONField(default=list)),
                ('estimate_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='TourismTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(default='My Tanzania trip', max_length=160)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ready', 'Ready to travel'), ('active', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('party_size', models.PositiveSmallIntegerField(default=2)),
                ('budget_tier', models.CharField(default='mid', max_length=32)),
                ('travel_style', models.CharField(default='leisure', max_length=32)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('tour_booking_ids', models.JSONField(blank=True, default=list)),
                ('stay_booking_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_itinerary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taifa_tourism.tourismitineraryversion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='tourismitineraryversion',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='taifa_tourism.tourismtrip'),
        ),
        migrations.AlterUniqueTogether(
            name='tourismitineraryversion',
            unique_together={('trip', 'version')},
        ),
    ]
