# Generated by Django 5.1.6 on 2026-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_phase3_financial_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargebackcase',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='liquiditysnapshot',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='settlement_currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='merchantsettlement',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='merchantstatement',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='treasurybankaccount',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
        migrations.AlterField(
            model_name='treasurytransfer',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], max_length=8),
        ),
    ]
