# Generated by Django 5.1.6 on 2026-07-18 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgricultureFarm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('farm_code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(db_index=True, max_length=128)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('crop_types', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('adapter_path', models.CharField(blank=True, default='ecosystem.ai.StubAiAdapter', max_length=255)),
                ('status', models.CharField(default='available', max_length=16)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='EcosystemWorkflowBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('domain_code', models.CharField(db_index=True, max_length=64)),
                ('workflow_definition_code', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('example_resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('route', models.CharField(blank=True, default='', max_length=128)),
                ('api_base', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='active', max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('required_services', models.JSONField(blank=True, default=list)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_code', models.SlugField(max_length=64, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('domains', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAuditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SharedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('api_base', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='production', max_length=16)),
                ('owner_team', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('target_url', models.URLField(max_length=512)),
                ('secret_hash', models.CharField(max_length=128)),
                ('secret_prefix', models.CharField(max_length=16)),
                ('event_types', models.JSONField(default=list)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgricultureListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(choices=[('produce', 'Produce'), ('input', 'Input'), ('equipment', 'Equipment')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('quantity_e2', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('price_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='open', max_length=16)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('logistics_shipment_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='taifa_ecosystem.agriculturefarm')),
            ],
        ),
        migrations.CreateModel(
            name='AiInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128)),
                ('domain_code', models.CharField(blank=True, default='', max_length=64)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('model_version', models.CharField(default='stub-v1', max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invocations', to='taifa_ecosystem.aicapability')),
            ],
        ),
        migrations.CreateModel(
            name='SuperAppModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('route', models.CharField(max_length=128)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('default_enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('category', models.CharField(default='service', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='taifa_ecosystem.industrydomain')),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PrincipalModuleEnablement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enablements', to='taifa_ecosystem.superappmodule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('principal', 'module'), name='taifa_ecosystem_unique_principal_module')],
            },
        ),
    ]
