# Generated by Django 5.1.6 on 2026-07-18 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0002_winga_brokerage_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('workflow_definition_code', models.CharField(default='winga.default_brokerage', help_text='enterprise.WorkflowDefinition.code', max_length=64)),
                ('default_commission_bps', models.PositiveIntegerField(default=500)),
                ('attributes_schema', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('customer_principal', models.CharField(db_index=True, max_length=128)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('inquiry', 'Inquiry'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('payment', 'Payment'), ('fulfillment', 'Fulfillment'), ('settlement', 'Settlement'), ('commission_payout', 'Commission Payout'), ('review', 'Review'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='lead', max_length=32)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('workflow_instance_id', models.UUIDField(blank=True, null=True)),
                ('booking', models.JSONField(blank=True, default=dict, help_text='Appointments/reservations payload (dates, guests, resources)')),
                ('fulfillment', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='winga.brokeragedomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='winga.brokeragedomain')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='winga.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('domain', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DealEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_stage', models.CharField(blank=True, default='', max_length=32)),
                ('to_stage', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='winga.brokeragedeal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_by', models.CharField(max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(default='open', max_length=16)),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='winga.brokeragedeal')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_principal', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('pipeline_stage', models.CharField(default='new', max_length=32)),
                ('priority_e4', models.PositiveIntegerField(default=5000)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='winga.brokeragedomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brokeragedeal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='winga.lead'),
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('booking', 'Booking'), ('rental', 'Rental'), ('digital', 'Digital'), ('referral', 'Referral'), ('logistics', 'Logistics'), ('other', 'Other')], default='service', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('price_minor', models.BigIntegerField(default=0)),
                ('compare_at_minor', models.BigIntegerField(blank=True, null=True)),
                ('inventory_qty', models.IntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('variants', models.JSONField(blank=True, default=list)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='winga.category')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='winga.brokeragedomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='winga.offering'),
        ),
        migrations.AddField(
            model_name='brokeragedeal',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='winga.offering'),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, default='', max_length=255)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='unverified', max_length=16)),
                ('kyb_ref', models.CharField(blank=True, default='', max_length=128)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('reputation_score_e4', models.PositiveIntegerField(default=5000)),
                ('risk_score_e4', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='providers', to='winga.brokeragedomain')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winga_providers', to='enterprise.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offering',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='winga.providerprofile'),
        ),
        migrations.AddField(
            model_name='brokeragedeal',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='winga.providerprofile'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('amount_minor', models.BigIntegerField()),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='winga.lead')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='winga.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brokeragedeal',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='winga.quotation'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_principal', models.CharField(db_index=True, max_length=128)),
                ('subject_type', models.CharField(max_length=16)),
                ('subject_id', models.UUIDField()),
                ('rating_e4', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='winga.brokeragedeal')),
            ],
        ),
        migrations.CreateModel(
            name='WingaProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('corporate_agency', 'Corporate Agency'), ('referral_org', 'Referral Org')], default='individual', max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='unverified', max_length=16)),
                ('kyc_ref', models.CharField(blank=True, default='', max_length=128)),
                ('certification', models.CharField(blank=True, default='', max_length=128)),
                ('reputation_score_e4', models.PositiveIntegerField(default=5000)),
                ('risk_score_e4', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(blank=True, related_name='wingas', to='winga.brokeragedomain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='winga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='winga.wingaprofile'),
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat'), ('tiered', 'Tiered'), ('category', 'Category'), ('provider', 'Provider'), ('campaign', 'Campaign'), ('referral_bonus', 'Referral Bonus'), ('multi_level', 'Multi Level')], default='percentage', max_length=32)),
                ('bps', models.PositiveIntegerField(default=500, help_text='Basis points when kind=percentage')),
                ('flat_minor', models.BigIntegerField(default=0)),
                ('tiers', models.JSONField(blank=True, default=list, help_text='[{"min_minor":0,"max_minor":100000,"bps":800}, ...]')),
                ('multi_level', models.JSONField(blank=True, default=list, help_text='[{"level":1,"bps":500},{"level":2,"bps":100}]')),
                ('campaign_code', models.CharField(blank=True, default='', max_length=64)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower wins')),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='winga.category')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='winga.brokeragedomain')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='winga.providerprofile')),
                ('winga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='winga.wingaprofile')),
            ],
            options={
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat'), ('tiered', 'Tiered'), ('category', 'Category'), ('provider', 'Provider'), ('campaign', 'Campaign'), ('referral_bonus', 'Referral Bonus'), ('multi_level', 'Multi Level')], max_length=32)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('basis_amount_minor', models.BigIntegerField()),
                ('commission_minor', models.BigIntegerField()),
                ('bps_applied', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('held', 'Held'), ('settled', 'Settled'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='calculated', max_length=16)),
                ('ledger_txn_id', models.CharField(blank=True, default='', max_length=64)),
                ('calculation', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='winga.brokeragedeal')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='winga.commissionrule')),
                ('winga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_events', to='winga.wingaprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brokeragedeal',
            name='winga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='winga.wingaprofile'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='winga.offering')),
            ],
            options={
                'unique_together': {('owner_principal', 'offering')},
            },
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['domain', 'active'], name='winga_offer_domain__25ae1b_idx'),
        ),
        migrations.AddIndex(
            model_name='offering',
            index=models.Index(fields=['kind', 'active'], name='winga_offer_kind_1aaab0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('deal', 'author_principal', 'subject_type')},
        ),
        migrations.AddIndex(
            model_name='brokeragedeal',
            index=models.Index(fields=['stage', 'domain'], name='winga_broke_stage_53a3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeragedeal',
            index=models.Index(fields=['winga', 'stage'], name='winga_broke_winga_i_912677_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeragedeal',
            index=models.Index(fields=['customer_principal', 'stage'], name='winga_broke_custome_792f6f_idx'),
        ),
    ]
