"""Canonical AI OS capability and agent catalog."""
from __future__ import annotations

CAPABILITIES = [
    # Shared platform
    {"code": "natural_language", "name": "Natural Language", "family": "nlp", "approval": False},
    {"code": "computer_vision", "name": "Computer Vision", "family": "vision", "approval": False},
    {"code": "ocr", "name": "OCR", "family": "vision", "approval": False},
    {"code": "speech_recognition", "name": "Speech Recognition", "family": "speech", "approval": False},
    {"code": "speech_synthesis", "name": "Speech Synthesis", "family": "speech", "approval": False},
    {"code": "recommendation", "name": "Recommendation Engine", "family": "reco", "approval": False},
    {"code": "fraud_detection", "name": "Fraud Detection", "family": "risk", "approval": True, "workflow": "ecosystem.business_verification"},
    {"code": "risk_scoring", "name": "Risk Scoring", "family": "risk", "approval": True, "workflow": "ecosystem.business_verification"},
    {"code": "forecasting", "name": "Forecasting", "family": "forecast", "approval": False},
    {"code": "optimization", "name": "Optimization", "family": "optimize", "approval": False},
    {"code": "classification", "name": "Classification", "family": "nlp", "approval": False},
    {"code": "semantic_search", "name": "Semantic Search", "family": "search", "approval": False},
    {"code": "knowledge_graph_query", "name": "Knowledge Graph", "family": "search", "approval": False},
    {"code": "embeddings", "name": "Embeddings", "family": "search", "approval": False},
    {"code": "translation", "name": "Translation", "family": "nlp", "approval": False},
    {"code": "document_intelligence", "name": "Document Intelligence", "family": "vision", "approval": False},
    # Domain-leaning
    {"code": "aml_monitoring", "name": "AML Monitoring", "family": "risk", "approval": True, "workflow": "ecosystem.business_verification"},
    {"code": "credit_scoring", "name": "Credit Scoring", "family": "risk", "approval": True, "workflow": "ecosystem.business_verification"},
    {"code": "liquidity_forecast", "name": "Liquidity Forecasting", "family": "forecast", "approval": False},
    {"code": "demand_forecast", "name": "Demand Forecasting", "family": "forecast", "approval": False},
    {"code": "eta_prediction", "name": "ETA Prediction", "family": "forecast", "approval": False},
    {"code": "dispatch_optimize", "name": "Dispatch Optimization", "family": "optimize", "approval": False},
    {"code": "clinical_doc_assist", "name": "Clinical Documentation Assist", "family": "nlp", "approval": False},
    {"code": "prescription_verify_support", "name": "Prescription Verification Support", "family": "vision", "approval": True, "workflow": "ecosystem.hospital_registration"},
    {"code": "inventory_forecast", "name": "Inventory Prediction", "family": "forecast", "approval": False},
    {"code": "pricing_optimize", "name": "Pricing Optimization", "family": "optimize", "approval": False},
    {"code": "permit_triage", "name": "Permit Triage", "family": "nlp", "approval": False},
    {"code": "personalized_learning", "name": "Personalized Learning", "family": "reco", "approval": False},
    {"code": "crop_planning", "name": "Crop Planning", "family": "forecast", "approval": False},
    {"code": "disease_image_recognition", "name": "Crop Disease Recognition", "family": "vision", "approval": False},
    {"code": "architecture_assist", "name": "Architecture Assistant", "family": "dev", "approval": False},
    {"code": "code_review_assist", "name": "Code Review Assist", "family": "dev", "approval": False},
    {"code": "incident_analysis", "name": "Incident Analysis", "family": "dev", "approval": False},
]

AGENTS = [
    {
        "code": "financial_agent",
        "name": "Financial Agent",
        "domain_code": "enterprise",
        "capabilities": [
            "fraud_detection",
            "aml_monitoring",
            "risk_scoring",
            "credit_scoring",
            "liquidity_forecast",
            "natural_language",
        ],
        "system_prompt": "Advise on financial risk and ops. Never post ledger entries. Escalate critical actions.",
    },
    {
        "code": "mobility_agent",
        "name": "Mobility Agent",
        "domain_code": "mobility",
        "capabilities": [
            "demand_forecast",
            "dispatch_optimize",
            "eta_prediction",
            "optimization",
            "forecasting",
        ],
        "system_prompt": "Optimize mobility demand, ETAs, and fleet. Do not alter dispatch engine state directly.",
    },
    {
        "code": "healthcare_agent",
        "name": "Healthcare Agent",
        "domain_code": "healthcare",
        "capabilities": [
            "clinical_doc_assist",
            "ocr",
            "prescription_verify_support",
            "document_intelligence",
            "forecasting",
        ],
        "system_prompt": "Non-diagnostic decision support only. Clinical liability remains with licensed practitioners.",
    },
    {
        "code": "government_agent",
        "name": "Government Agent",
        "domain_code": "government",
        "capabilities": ["permit_triage", "semantic_search", "document_intelligence", "classification"],
        "system_prompt": "Assist citizens and officers with permits and knowledge. Cite policy sources.",
    },
    {
        "code": "commerce_agent",
        "name": "Commerce Agent",
        "domain_code": "commerce",
        "capabilities": ["recommendation", "inventory_forecast", "pricing_optimize", "forecasting"],
        "system_prompt": "Advise merchants on inventory, pricing, and demand.",
    },
    {
        "code": "agriculture_agent",
        "name": "Agriculture Agent",
        "domain_code": "agriculture",
        "capabilities": ["crop_planning", "disease_image_recognition", "forecasting", "optimization"],
        "system_prompt": "Advise farmers with weather-aware, evidence-backed recommendations.",
    },
    {
        "code": "education_agent",
        "name": "Education Agent",
        "domain_code": "education",
        "capabilities": ["personalized_learning", "recommendation", "forecasting"],
        "system_prompt": "Personalize learning paths; protect student PII.",
    },
    {
        "code": "enterprise_ops_agent",
        "name": "Enterprise Operations Agent",
        "domain_code": "enterprise",
        "capabilities": ["classification", "document_intelligence", "natural_language", "forecasting"],
        "system_prompt": "Draft operational summaries and route routine work.",
    },
    {
        "code": "developer_agent",
        "name": "Developer Agent",
        "domain_code": "enterprise",
        "capabilities": ["architecture_assist", "code_review_assist", "incident_analysis", "natural_language"],
        "system_prompt": "Assist engineers. Never expose secrets or production credentials.",
    },
    {
        "code": "citizen_assistant",
        "name": "Citizen Assistant",
        "domain_code": "government",
        "capabilities": ["natural_language", "semantic_search", "translation", "speech_synthesis"],
        "system_prompt": "Help Tanzanian citizens in Swahili and English. Cite official sources when advising.",
    },
]

KNOWLEDGE_SEED = [
    {
        "code": "policy-payments-human-approval",
        "title": "Critical financial actions require human approval",
        "category": "policy",
        "domain_code": "enterprise",
        "body": "AI recommendations affecting ledger, settlement, or AML holds require configurable human approval via enterprise workflow. AI never posts journal entries.",
        "citation": "Taifa Responsible AI Policy §4",
    },
    {
        "code": "reg-latra-passenger-safety",
        "title": "Passenger safety obligations for public service vehicles",
        "category": "regulation",
        "domain_code": "mobility",
        "body": "Operators must maintain licensed vehicles, verified drivers, and incident reporting. Station-based dispatch improves accountability.",
        "citation": "LATRA operational guidance (summary)",
    },
    {
        "code": "manual-mobility-dispatch",
        "title": "Station-first dispatch overview",
        "category": "manual",
        "domain_code": "mobility",
        "body": "Trips prefer station queue drivers within service radius, then overflow and nearby. Emergency trips use priority strategies.",
        "citation": "MOBILITY_DISPATCH_ALGORITHMS.md",
    },
    {
        "code": "policy-healthcare-non-diagnostic",
        "title": "Healthcare AI is non-diagnostic",
        "category": "policy",
        "domain_code": "healthcare",
        "body": "Clinical documentation and OCR assist clinicians. Diagnosis and prescribing authority remain with licensed practitioners.",
        "citation": "Taifa Healthcare AI Policy §2",
    },
    {
        "code": "manual-gov-permit-triage",
        "title": "Permit application triage",
        "category": "procedure",
        "domain_code": "government",
        "body": "Incoming permit applications are classified by type, completeness, and urgency before routing to the correct LGA queue.",
        "citation": "Government Integration Guide",
    },
    {
        "code": "agri-market-basics",
        "title": "Produce marketplace settlement",
        "category": "business",
        "domain_code": "agriculture",
        "body": "Farm listings settle through Taifa Payments references. Logistics use Mobility shipments for last-mile and freight.",
        "citation": "DIGITAL_ECOSYSTEM.md",
    },
]

MODELS = [
    {"code": "taifa-nlp-stub", "name": "Taifa NLP Stub", "modality": "text", "version": "1.0.0"},
    {"code": "taifa-vision-stub", "name": "Taifa Vision Stub", "modality": "vision", "version": "1.0.0"},
    {"code": "taifa-speech-stub", "name": "Taifa Speech Stub", "modality": "speech", "version": "1.0.0"},
    {"code": "taifa-tabular-stub", "name": "Taifa Tabular Stub", "modality": "tabular", "version": "1.0.0"},
    {"code": "taifa-multimodal-stub", "name": "Taifa Multimodal Stub", "modality": "multimodal", "version": "1.0.0"},
]

AUTOMATIONS = [
    {
        "code": "doc_classify_inbox",
        "name": "Document classification",
        "domain_code": "enterprise",
        "trigger_event": "document.uploaded",
        "capability_code": "classification",
        "auto_apply": False,
    },
    {
        "code": "ticket_route",
        "name": "Support ticket routing",
        "domain_code": "enterprise",
        "trigger_event": "ticket.created",
        "capability_code": "classification",
        "auto_apply": True,
    },
    {
        "code": "compliance_reminder_draft",
        "name": "Compliance reminder drafting",
        "domain_code": "government",
        "trigger_event": "compliance.due",
        "capability_code": "natural_language",
        "auto_apply": False,
    },
    {
        "code": "ops_summary_daily",
        "name": "Operational summary",
        "domain_code": "enterprise",
        "trigger_event": "ops.daily",
        "capability_code": "natural_language",
        "auto_apply": False,
    },
]
