# Generated by Django 5.1.6 on 2026-07-19 06:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0002_winga_brokerage_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('groceries', 'Groceries'), ('pharmacy', 'Pharmacy'), ('hardware', 'Hardware'), ('electronics', 'Electronics'), ('home', 'Home'), ('baby', 'Baby'), ('pets', 'Pets'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('bakery', 'Bakery'), ('restaurant', 'Restaurant'), ('fashion', 'Fashion'), ('stationery', 'Stationery'), ('other', 'Other')], default='groceries', max_length=32)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('banner_url', models.URLField(blank=True, default='')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('delivery_radius_m', models.PositiveIntegerField(default=3000)),
                ('prep_minutes', models.PositiveIntegerField(default=15)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('reliability', models.DecimalField(decimal_places=2, default=0.9, max_digits=3)),
                ('workload', models.PositiveIntegerField(default=0)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('verified', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='express_stores', to='enterprise.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('price_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('stock_qty', models.PositiveIntegerField(default=10)),
                ('stock_status', models.CharField(default='available', max_length=24)),
                ('image_url', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='express.expressstore')),
            ],
        ),
        migrations.CreateModel(
            name='ExpressOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(db_index=True, max_length=48, unique=True)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ranked', 'Ranked'), ('placed', 'Placed'), ('merchant_accepted', 'Merchant Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('rider_assigned', 'Rider Assigned'), ('picked_up', 'Picked Up'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('subtotal_minor', models.PositiveBigIntegerField(default=0)),
                ('delivery_fee_minor', models.PositiveBigIntegerField(default=0)),
                ('total_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('customer_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('customer_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('customer_address', models.CharField(blank=True, default='', max_length=255)),
                ('ranking', models.JSONField(blank=True, default=list)),
                ('food_order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('mos_order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('trip_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('tap_session_code', models.CharField(blank=True, default='', max_length=48)),
                ('eta_minutes', models.PositiveIntegerField(default=0)),
                ('merchant_notes', models.TextField(blank=True, default='')),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('ai_prompt', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='express.expressstore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expressstore',
            index=models.Index(fields=['category', 'active'], name='express_exp_categor_0a95c5_idx'),
        ),
        migrations.AddIndex(
            model_name='expressproduct',
            index=models.Index(fields=['name', 'active'], name='express_exp_name_081a70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expressproduct',
            unique_together={('store', 'sku')},
        ),
        migrations.AddIndex(
            model_name='expressorder',
            index=models.Index(fields=['owner', 'status'], name='express_exp_owner_b87619_idx'),
        ),
    ]
