# Generated by Django 5.1.6 on 2026-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expressorder',
            name='customer_notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='delivery_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='delivery_pin',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='package_code',
            field=models.CharField(blank=True, default='', max_length=48, unique=True),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='package_qr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='packing_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='payment_method',
            field=models.CharField(blank=True, default='wallet', max_length=24),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='payment_timing',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('on_delivery', 'On Delivery')], default='prepaid', max_length=16),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='platform_fee_minor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='settlement_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='settlement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('allocated', 'Allocated'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='expressorder',
            name='urgency',
            field=models.CharField(blank=True, default='standard', max_length=16),
        ),
        migrations.AlterField(
            model_name='expressorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ranked', 'Ranked'), ('placed', 'Placed'), ('merchant_found', 'Merchant Found'), ('merchant_accepted', 'Merchant Accepted'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('rider_assigned', 'Rider Assigned'), ('rider_arriving', 'Rider Arriving'), ('picked_up', 'Picked Up'), ('delivering', 'Delivering'), ('arriving', 'Arriving'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=32),
        ),
    ]
