# Generated by Django 5.1.6 on 2026-08-06 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('administrator', 'Administrator'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('auditor', 'Auditor'), ('support', 'Support')], default='cashier', max_length=32)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='invited', max_length=32)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taifa_merchant_employee',
            },
        ),
        migrations.CreateModel(
            name='MerchantIdentityUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email_verified', models.BooleanField(default=False)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taifa_merchant_identity_user',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('tnpi_branch_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to='taifa_merchant.employee')),
            ],
            options={
                'db_table': 'taifa_merchant_branch',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tnpi_merchant_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('legal_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_verification', 'Pending verification'), ('verified', 'Verified'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='draft', max_length=32)),
                ('verification_status', models.CharField(choices=[('not_started', 'Not started'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_info', 'Needs information')], default='not_started', max_length=32)),
                ('owner_identity_user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'taifa_merchant_account',
                'indexes': [models.Index(fields=['status', 'verification_status'], name='taifa_merch_status_f25d82_idx')],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='taifa_merchant.merchant'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('pos', 'POS terminal'), ('other', 'Other')], default='mobile', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='pending', max_length=32)),
                ('health', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='unknown', max_length=32)),
                ('ownership', models.CharField(blank=True, default='merchant', max_length=128)),
                ('hardware_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('tnpi_device_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='taifa_merchant.branch')),
                ('registered_by_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_devices', to='taifa_merchant.employee')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_device',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='taifa_merchant.merchant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_identity_user_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=128)),
                ('resource_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_audit_log',
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category', models.CharField(blank=True, default='', max_length=128)),
                ('tin', models.CharField(blank=True, default='', max_length=64)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('country', models.CharField(default='TZ', max_length=2)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('logo_s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_profile',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['merchant', 'status'], name='taifa_merch_merchan_b26633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('merchant', 'email')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['merchant', 'status'], name='taifa_merch_merchan_f865e8_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['merchant', 'is_active'], name='taifa_merch_merchan_2a5b7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('merchant', 'code')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['merchant', 'created_at'], name='taifa_merch_merchan_cd16a7_idx'),
        ),
    ]
