# Generated by Django 5.1.6 on 2026-08-06 13:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taifa_merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('android_phone', 'Android phone'), ('android_tablet', 'Android tablet'), ('pos', 'POS terminal'), ('desktop_terminal', 'Desktop terminal'), ('other', 'Other')], default='mobile', max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], default='invited', max_length=32),
        ),
        migrations.CreateModel(
            name='BranchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('device_count', models.PositiveIntegerField(default=0)),
                ('activity_score', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='taifa_merchant.branch')),
            ],
            options={
                'db_table': 'taifa_merchant_branch_statistics',
            },
        ),
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_permissions', models.JSONField(blank=True, default=list)),
                ('denied_permissions', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='taifa_merchant.employee')),
            ],
            options={
                'db_table': 'taifa_merchant_employee_permissions',
            },
        ),
        migrations.CreateModel(
            name='MerchantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='sw', max_length=16)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('business_preferences', models.JSONField(blank=True, default=dict)),
                ('payment_preferences', models.JSONField(blank=True, default=dict)),
                ('receipt_branding', models.JSONField(blank=True, default=dict)),
                ('tax_settings', models.JSONField(blank=True, default=dict)),
                ('regional_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('system_alerts', models.BooleanField(default=True)),
                ('merchant_announcements', models.BooleanField(default=True)),
                ('device_alerts', models.BooleanField(default=True)),
                ('verification_alerts', models.BooleanField(default=True)),
                ('channels', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by_identity_user_id', models.UUIDField(blank=True, null=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_assignments', to='taifa_merchant.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taifa_merchant.branch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='taifa_merchant.device')),
            ],
            options={
                'db_table': 'taifa_merchant_device_assignment',
                'indexes': [models.Index(fields=['device', 'is_active'], name='taifa_merch_device__adebc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_identity_user_id', models.UUIDField(blank=True, null=True)),
                ('activity_type', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taifa_merchant.branch')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_activity',
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='taifa_merch_merchan_2285ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='system', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_notification',
                'indexes': [models.Index(fields=['merchant', 'is_read', 'created_at'], name='taifa_merch_merchan_133668_idx')],
            },
        ),
    ]
