# Generated by Django 5.1.6 on 2026-08-06 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taifa_merchant', '0002_sprint2_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tnpi_terminal_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('ready', 'Ready'), ('busy', 'Busy'), ('offline', 'Offline')], default='inactive', max_length=32)),
                ('softpos_settings', models.JSONField(blank=True, default=dict)),
                ('offline_queue_enabled', models.BooleanField(default=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal', to='taifa_merchant.device')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_terminal',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tnpi_payment_id', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(choices=[('softpos', 'SoftPOS / Tap to Pay'), ('qr_static', 'Static QR'), ('qr_dynamic', 'Dynamic QR'), ('payment_link', 'Payment link')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('voided', 'Voided'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='pending', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('merchant_reference', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('authorization_code', models.CharField(blank=True, default='', max_length=32)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taifa_merchant.branch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taifa_merchant.device')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='taifa_merchant.merchant')),
            ],
            options={
                'db_table': 'taifa_merchant_payment_transaction',
            },
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tnpi_link_id', models.CharField(db_index=True, max_length=64)),
                ('url', models.URLField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='active', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('share_channels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='taifa_merchant.merchant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_links', to='taifa_merchant.paymenttransaction')),
            ],
            options={
                'db_table': 'taifa_merchant_payment_link',
            },
        ),
        migrations.CreateModel(
            name='QRPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tnpi_qr_id', models.CharField(db_index=True, max_length=64)),
                ('qr_type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic'), ('merchant', 'Merchant'), ('customer', 'Customer'), ('invoice', 'Invoice')], max_length=32)),
                ('payload', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to='taifa_merchant.merchant')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_sessions', to='taifa_merchant.paymenttransaction')),
            ],
            options={
                'db_table': 'taifa_merchant_qr_payment',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=64, unique=True)),
                ('pdf_s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('verification_code', models.CharField(db_index=True, max_length=32)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('shared_via', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='taifa_merchant.merchant')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='taifa_merchant.paymenttransaction')),
            ],
            options={
                'db_table': 'taifa_merchant_receipt',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tnpi_refund_id', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('is_void', models.BooleanField(default=False)),
                ('actor_identity_user_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='taifa_merchant.merchant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='taifa_merchant.paymenttransaction')),
            ],
            options={
                'db_table': 'taifa_merchant_refund',
            },
        ),
        migrations.CreateModel(
            name='TransactionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('actor_identity_user_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_audits', to='taifa_merchant.merchant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='taifa_merchant.paymenttransaction')),
            ],
            options={
                'db_table': 'taifa_merchant_transaction_audit',
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant', 'created_at'], name='taifa_merch_merchan_018f95_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['merchant', 'status'], name='taifa_merch_merchan_b5915f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionaudit',
            index=models.Index(fields=['transaction', 'created_at'], name='taifa_merch_transac_1a5aea_idx'),
        ),
    ]
