# Generated by Django 5.1.6 on 2026-07-14 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('requesting', 'Requesting'), ('searching', 'Searching'), ('driver_assigned', 'Driver Assigned'), ('driver_en_route', 'Driver En Route'), ('driver_arrived', 'Driver Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_confirmed', 'Payment Confirmed')], default='requesting', max_length=32)),
                ('pickup_name', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_name', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('product_id', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=64)),
                ('fare_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('driver_name', models.CharField(blank=True, default='', max_length=128)),
                ('vehicle_label', models.CharField(blank=True, default='', max_length=128)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('distance_meters', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
