# Generated by Django 5.1.6 on 2026-07-17 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_national_mobility_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_bps', models.PositiveIntegerField(default=0)),
                ('maximum_discount_minor', models.PositiveBigIntegerField(default=0)),
                ('trip_kind', models.CharField(blank=True, choices=[('passenger', 'Passenger'), ('delivery', 'Delivery'), ('corporate', 'Corporate'), ('government', 'Government'), ('emergency', 'Emergency')], default='', max_length=16)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('usage_limit', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='trips_promotion_end_after_start'), models.CheckConstraint(condition=models.Q(('discount_bps__lte', 10000)), name='trips_promotion_discount_max_100_percent')],
            },
        ),
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trips.driver')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_schedules', to='trips.station')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'starts_at', 'ends_at'], name='trips_drive_driver__d11271_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='trips_schedule_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='VehicleOperationalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('odometer_km', models.PositiveBigIntegerField(default=0)),
                ('quantity_e2', models.PositiveBigIntegerField(default=0)),
                ('cost_minor', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('BTC', 'Bitcoin')], default='TZS', max_length=8)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_logs', to='trips.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_logs', to='trips.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'kind', '-occurred_at'], name='trips_vehic_vehicle_61343c_idx')],
            },
        ),
    ]
