# Generated by Django 5.1.6 on 2026-07-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_fleet_operations_and_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='verification_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
