# Generated by Django 5.1.6 on 2026-07-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_phase3_financial_platform'),
        ('payments', '0007_phase3_financial_platform'),
        ('trips', '0004_strengthen_delivery_verification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(condition=models.Q(('rating_e2__lte', 500)), name='trips_driver_rating_max'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(condition=models.Q(('safety_score_e2__lte', 500)), name='trips_driver_safety_score_max'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(condition=models.Q(('acceptance_rate_e4__lte', 10000)), name='trips_driver_acceptance_rate_max'),
        ),
        migrations.AddConstraint(
            model_name='driverlocation',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='trips_location_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='driverlocation',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='trips_location_valid_longitude'),
        ),
        migrations.AddConstraint(
            model_name='driverlocation',
            constraint=models.CheckConstraint(condition=models.Q(('heading_degrees__lte', 359)), name='trips_location_valid_heading'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='trips_station_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='trips_station_valid_longitude'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('fare_minor__gte', 0)), name='trips_fare_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_lat__gte', -90), ('pickup_lat__lte', 90)), name='trips_pickup_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_lng__gte', -180), ('pickup_lng__lte', 180)), name='trips_pickup_valid_longitude'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_lat__gte', -90), ('dropoff_lat__lte', 90)), name='trips_dropoff_valid_latitude'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_lng__gte', -180), ('dropoff_lng__lte', 180)), name='trips_dropoff_valid_longitude'),
        ),
    ]
