# Generated by Django 5.1.6 on 2026-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_mobility_data_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='registry_approval_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='registry_approval_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='station',
            name='registry_approval_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='station',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registry_approval_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
