# Generated by Django 5.1.6 on 2026-07-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_national_mobility_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_type',
            field=models.CharField(choices=[('independent', 'Independent'), ('small', 'Small'), ('corporate', 'Corporate'), ('government', 'Government'), ('business', 'Business'), ('rental', 'Rental')], max_length=24),
        ),
    ]
