# Generated by Django 5.1.6 on 2026-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_add_business_fleet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('active', 'Active'), ('expired_insurance', 'Expired Insurance'), ('expired_road_license', 'Expired Road License'), ('expired_inspection', 'Expired Inspection'), ('maintenance', 'Maintenance'), ('suspended', 'Suspended'), ('retired', 'Retired')], default='pending', max_length=24),
        ),
    ]
