# Generated by Django 5.1.6 on 2026-07-18 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_registry_vehicle_compliance_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='availability',
            field=models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('offered', 'Offered'), ('on_trip', 'On Trip'), ('break', 'Break'), ('busy', 'Busy'), ('emergency', 'Emergency')], default='offline', max_length=16),
        ),
        migrations.CreateModel(
            name='MobilityNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_principal', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('deduplication_key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trips.station')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='trips.trip')),
            ],
        ),
    ]
