# Generated by Django 5.1.6 on 2026-07-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_mdmp_notifications_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
