# Generated by Django 5.1.6 on 2026-07-18 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_mdmp_trip_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilityZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(db_index=True, max_length=128)),
                ('district', models.CharField(db_index=True, max_length=128)),
                ('ward', models.CharField(blank=True, default='', max_length=128)),
                ('polygon', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringRidePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('pickup_name', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_name', models.CharField(max_length=255)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vehicle_mode', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bajaji', 'Bajaji'), ('taxi', 'Taxi'), ('private_car', 'Private Car'), ('van', 'Van'), ('pickup', 'Pickup'), ('truck', 'Truck'), ('bus', 'Bus'), ('electric_vehicle', 'Electric Vehicle')], default='motorcycle', max_length=24)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('estimated_distance_meters', models.PositiveIntegerField(default=0)),
                ('estimated_duration_seconds', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(default='wallet', max_length=24)),
                ('corporate_account', models.CharField(blank=True, default='', max_length=128)),
                ('weekdays', models.JSONField(default=list)),
                ('local_time', models.TimeField()),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_materialized_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobilityAccountLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.SlugField(max_length=64)),
                ('account_type', models.CharField(choices=[('family', 'Family'), ('corporate', 'Corporate')], max_length=16)),
                ('member_principal', models.CharField(db_index=True, max_length=128)),
                ('role', models.CharField(default='member', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account_code', 'member_principal'), name='trips_unique_account_member')],
            },
        ),
        migrations.CreateModel(
            name='MobilityFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(db_index=True, max_length=128)),
                ('subject_type', models.CharField(choices=[('driver', 'Driver'), ('station', 'Station')], max_length=16)),
                ('subject_id', models.CharField(db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'subject_type', 'subject_id'), name='trips_unique_mobility_favorite')],
            },
        ),
        migrations.CreateModel(
            name='RegionalSupervisorAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128)),
                ('scope', models.CharField(choices=[('region', 'Region'), ('district', 'District'), ('zone', 'Zone')], max_length=16)),
                ('region', models.CharField(db_index=True, max_length=128)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('role_title', models.CharField(default='regional_supervisor', max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='trips.mobilityzone')),
            ],
            options={
                'indexes': [models.Index(fields=['principal', 'active', 'region'], name='trips_regio_princip_12ce4e_idx')],
            },
        ),
    ]
