# Generated by Django 5.1.6 on 2026-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_seed_national_mode_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercitybooking',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='intercitydeparture',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='publictransittimetable',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='transportticket',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
        migrations.AlterField(
            model_name='vehicleoperationallog',
            name='currency',
            field=models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('BIF', 'Burundian Franc'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha'), ('CDF', 'Congolese Franc'), ('BTC', 'Bitcoin')], default='TZS', max_length=8),
        ),
    ]
