# Generated by Django 5.1.6 on 2026-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_brt_phase4_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('region', models.CharField(db_index=True, max_length=128)),
                ('route_code', models.CharField(blank=True, default='', max_length=64)),
                ('product_code', models.CharField(blank=True, default='', max_length=64)),
                ('tickets_issued', models.PositiveIntegerField(default=0)),
                ('tickets_validated', models.PositiveIntegerField(default=0)),
                ('nfc_validations', models.PositiveIntegerField(default=0)),
                ('qr_validations', models.PositiveIntegerField(default=0)),
                ('fare_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='transitavlvehicle',
            new_name='trips_trans_route_i_0ffd3b_idx',
            old_name='trips_trans_route_i_6f4a21_idx',
        ),
        migrations.RenameIndex(
            model_name='transitscheduledrun',
            new_name='trips_trans_driver__f8e655_idx',
            old_name='trips_trans_driver__a8f2c1_idx',
        ),
        migrations.AddConstraint(
            model_name='transitdailymetric',
            constraint=models.UniqueConstraint(fields=('date', 'region', 'route_code', 'product_code'), name='trips_unique_transit_daily_metric'),
        ),
    ]
