# Generated by Django 5.1.6 on 2026-07-23 16:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_brt_phase5_ops_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitFamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guardian_owner', models.CharField(db_index=True, max_length=128)),
                ('member_owner', models.CharField(db_index=True, max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('relationship', models.CharField(choices=[('child', 'Child'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('other', 'Other')], default='child', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], db_index=True, default='active', max_length=16)),
                ('can_purchase', models.BooleanField(default=True)),
                ('monthly_limit_minor', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('guardian_owner', 'member_owner'), name='trips_unique_transit_family_member')],
            },
        ),
    ]
