# Generated by Django 5.1.6 on 2026-07-23 17:50

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_brt_phase7_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitLostFoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_owner', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], db_index=True, max_length=8)),
                ('category', models.CharField(choices=[('phone', 'Phone'), ('wallet', 'Wallet'), ('bag', 'Bag'), ('id_card', 'Id Card'), ('clothing', 'Clothing'), ('keys', 'Keys'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('stop_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('matched', 'Matched'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('contact_hint', models.CharField(blank=True, default='', max_length=128)),
                ('claimant_owner', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('claim_message', models.TextField(blank=True, default='')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_found_items', to='trips.publictransitroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
