# Generated by Django 5.1.6 on 2026-07-18 13:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('official_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='active', max_length=16)),
                ('default_currency', models.CharField(max_length=8)),
                ('supported_currencies', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('default_locale', models.CharField(default='en', max_length=16)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('data_region', models.CharField(default='eastafrica', max_length=64)),
                ('calling_code', models.CharField(blank=True, default='', max_length=8)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LanguagePack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('rtl', models.BooleanField(default=False)),
                ('strings', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerNetworkMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_code', models.SlugField(max_length=64, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('partner_type', models.CharField(max_length=32)),
                ('countries', models.JSONField(default=list)),
                ('domains', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('certification_tier', models.CharField(blank=True, default='', max_length=16)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrossBorderCorridor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('corridor_type', models.CharField(default='wallet', max_length=32)),
                ('origin_currency', models.CharField(max_length=8)),
                ('destination_currency', models.CharField(max_length=8)),
                ('settlement_currency', models.CharField(default='USD', max_length=8)),
                ('fee_bps', models.PositiveIntegerField(default=50)),
                ('min_fee_minor', models.PositiveBigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('routing', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridors_in', to='taifa_continental.countryprofile')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridors_out', to='taifa_continental.countryprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CrossBorderTransferIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=8)),
                ('converted_minor', models.PositiveBigIntegerField(default=0)),
                ('converted_currency', models.CharField(blank=True, default='', max_length=8)),
                ('fx_rate_e8', models.PositiveBigIntegerField(default=0)),
                ('fee_minor', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(default='quoted', max_length=16)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('compliance_flags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intents', to='taifa_continental.crossbordercorridor')),
            ],
        ),
        migrations.CreateModel(
            name='DataResidencyPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_region', models.CharField(max_length=64)),
                ('allow_cross_border_processing', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=2555)),
                ('backup_region', models.CharField(blank=True, default='', max_length=64)),
                ('encryption_profile', models.CharField(default='aes-256-gcm', max_length=64)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residency_policy', to='taifa_continental.countryprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(db_index=True, max_length=8)),
                ('quote_currency', models.CharField(db_index=True, max_length=8)),
                ('rate_e8', models.PositiveBigIntegerField()),
                ('source', models.CharField(default='seed', max_length=64)),
                ('as_of', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-as_of'], name='taifa_conti_base_cu_b83e1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityFederationBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.SlugField(max_length=64)),
                ('provider_type', models.CharField(max_length=32)),
                ('adapter_path', models.CharField(default='continental.adapters.StubIdentityAdapter', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_bindings', to='taifa_continental.countryprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperSandboxCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key_prefix', models.CharField(max_length=16)),
                ('api_key_hash', models.CharField(max_length=128, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_credentials', to='taifa_continental.partnernetworkmember')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRailBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rail_code', models.SlugField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('currencies', models.JSONField(default=list)),
                ('adapter_path', models.CharField(blank=True, default='', max_length=255)),
                ('sandbox', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_rails', to='taifa_continental.countryprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalOpsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('domain_code', models.CharField(blank=True, default='', max_length=64)),
                ('kpi_code', models.CharField(max_length=64)),
                ('value_e2', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'country_code', 'domain_code', 'kpi_code'), name='taifa_continental_unique_regional_kpi')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('rules', models.JSONField(default=dict)),
                ('reporting_authority', models.CharField(blank=True, default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profiles', to='taifa_continental.countryprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('country', 'code', 'version'), name='taifa_continental_unique_compliance')],
            },
        ),
    ]
