# Generated by Django 5.1.6 on 2026-07-21 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0014_alter_intercitybooking_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('push', 'Push'), ('sms', 'Sms'), ('ussd', 'Ussd'), ('ivr', 'Ivr'), ('stage', 'Stage')], max_length=16)),
                ('msisdn_hash', models.CharField(db_index=True, max_length=64)),
                ('body', models.TextField()),
                ('parsed_action', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msisdn_hash', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(default='root', max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripBoardingPin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin_hash', models.CharField(max_length=128)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_pin', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelDispatchAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('push', 'Push'), ('sms', 'Sms'), ('ussd', 'Ussd'), ('ivr', 'Ivr'), ('stage', 'Stage')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('responded', 'Responded'), ('timeout', 'Timeout')], default='pending', max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_attempts', to='trips.driver')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_attempts', to='trips.dispatchoffer')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_attempts', to='trips.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['offer', 'channel'], name='mobility_ch_offer_i_ff0838_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverChannelBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msisdn', models.CharField(blank=True, default='', max_length=20)),
                ('msisdn_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('device_capability', models.CharField(choices=[('smartphone', 'Smartphone'), ('feature_phone', 'Feature Phone')], default='smartphone', max_length=16)),
                ('has_internet', models.BooleanField(default=True)),
                ('has_gps', models.BooleanField(default=True)),
                ('push_token', models.CharField(blank=True, default='', max_length=255)),
                ('preferred_channel', models.CharField(blank=True, choices=[('push', 'Push'), ('sms', 'Sms'), ('ussd', 'Ussd'), ('ivr', 'Ivr'), ('stage', 'Stage')], default='', max_length=16)),
                ('battery_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_binding', to='trips.driver')),
            ],
            options={
                'indexes': [models.Index(fields=['msisdn_hash', 'device_capability'], name='mobility_ch_msisdn__7be496_idx')],
            },
        ),
    ]
