# Generated by Django 5.1.6 on 2026-07-22 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('winga', '0001_winga_brokerage_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'property categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('landlord', 'Landlord'), ('agent', 'Agent'), ('developer', 'Developer')], default='owner', max_length=16)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=16)),
                ('kyc_ref', models.CharField(blank=True, default='', max_length=128)),
                ('bio', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('filters', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('lease', 'Lease')], default='rent', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('price_minor', models.BigIntegerField(default=0)),
                ('deposit_minor', models.BigIntegerField(default=0)),
                ('beds', models.PositiveSmallIntegerField(default=0)),
                ('baths', models.PositiveSmallIntegerField(default=0)),
                ('area_sqm', models.PositiveIntegerField(default=0)),
                ('address_line', models.CharField(blank=True, default='', max_length=255)),
                ('ward', models.CharField(blank=True, default='', max_length=128)),
                ('district', models.CharField(blank=True, default='', max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='winga_property.propertycategory')),
                ('winga_offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_listings', to='winga.offering')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='winga_property.propertyowner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=16)),
                ('url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='winga_property.propertylisting')),
            ],
            options={
                'verbose_name_plural': 'property media',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='winga_property.propertycategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='winga_property.propertytype'),
        ),
        migrations.CreateModel(
            name='PropertyVerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('actor', models.CharField(max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_events', to='winga_property.propertylisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='winga_property.propertylisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('principal', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['active', 'verification_status'], name='winga_prope_active_e96308_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['region', 'district'], name='winga_prope_region_ceb171_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['transaction_type', 'price_minor'], name='winga_prope_transac_280854_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['latitude', 'longitude'], name='winga_prope_latitud_e661d6_idx'),
        ),
    ]
