# Generated by Django 5.1.6 on 2026-07-22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winga_property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyViewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("principal", models.CharField(db_index=True, max_length=128)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="winga_property.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["principal", "-viewed_at"],
                        name="winga_prope_princip_0f8c0d_idx",
                    )
                ],
            },
        ),
    ]
