# Generated by Django 5.1.6 on 2026-07-22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("winga_property", "0002_propertyviewevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertymedia",
            name="floor_plan_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="is_hd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="panorama_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="room_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("living", "Living"),
                    ("kitchen", "Kitchen"),
                    ("bedroom", "Bedroom"),
                    ("bathroom", "Bathroom"),
                    ("parking", "Parking"),
                    ("compound", "Compound"),
                    ("exterior", "Exterior"),
                    ("other", "Other"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="propertymedia",
            name="tour_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gallery", "Gallery"),
                    ("walkthrough", "Walkthrough"),
                    ("video_tour", "Video Tour"),
                    ("guided_tour", "Guided Tour"),
                    ("floor_plan", "Floor Plan"),
                    ("panorama_360", "Panorama 360"),
                ],
                default="gallery",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PropertyViewingPass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("principal", models.CharField(db_index=True, max_length=128)),
                (
                    "plan_code",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("bundle", "Bundle"),
                            ("unlimited", "Unlimited"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("amount_minor", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="TZS", max_length=8)),
                ("payment_ref", models.CharField(blank=True, default="", max_length=64)),
                ("qr_token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("listings_unlocked", models.JSONField(blank=True, default=list)),
                ("unlock_address", models.BooleanField(default=False)),
                ("unlock_navigation", models.BooleanField(default=False)),
                ("unlock_contact", models.BooleanField(default=False)),
                ("unlock_scheduling", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viewing_passes",
                        to="winga_property.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["principal", "status"],
                        name="winga_prope_princip_6a2f1a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PropertyLiveSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("customer_principal", models.CharField(db_index=True, max_length=128)),
                ("owner_principal", models.CharField(db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("join_code", models.CharField(db_index=True, max_length=16, unique=True)),
                ("stream_url", models.URLField(blank=True, default="", max_length=500)),
                ("recording_url", models.URLField(blank=True, default="", max_length=500)),
                ("ai_transcript", models.JSONField(blank=True, default=dict)),
                ("appointment_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="winga_property.propertylisting",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="PropertyLiveMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sender_principal", models.CharField(max_length=128)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="winga_property.propertylivesession",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
