# Generated by Django 5.1.6 on 2026-07-22 08:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winga_property', '0004_phase4_human_winga'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applicant_principal', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=16)),
                ('employment_status', models.CharField(blank=True, default='', max_length=64)),
                ('monthly_income_minor', models.BigIntegerField(default=0)),
                ('national_id', models.CharField(blank=True, default='', max_length=64)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyApplicationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('national_id', 'National Id'), ('payslip', 'Payslip'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('other', 'Other')], default='other', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('uploaded_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyApplicationVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_kind', models.CharField(choices=[('identity', 'Identity'), ('income', 'Income')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['check_kind'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_principal', models.CharField(db_index=True, max_length=128)),
                ('owner_principal', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signatures', 'Pending Signatures'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('rent_minor', models.BigIntegerField(default=0)),
                ('deposit_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_text', models.TextField(blank=True, default='')),
                ('contract_url', models.URLField(blank=True, default='', max_length=500)),
                ('tenant_signed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLeasePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('first_rent', 'First Rent'), ('monthly_rent', 'Monthly Rent'), ('renewal', 'Renewal')], max_length=16)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending_payment', max_length=20)),
                ('amount_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMoveWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('move_in', 'Move In'), ('move_out', 'Move Out')], max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='propertyviewevent',
            new_name='winga_prope_princip_2844af_idx',
            old_name='winga_prope_princip_0f8c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyviewingpass',
            new_name='winga_prope_princip_b4afcd_idx',
            old_name='winga_prope_princip_6a2f1a_idx',
        ),
        migrations.RenameIndex(
            model_name='propertywingaassignment',
            new_name='winga_prope_custome_fdc692_idx',
            old_name='winga_prope_custome_8b4e2a_idx',
        ),
        migrations.AlterField(
            model_name='propertytimelineevent',
            name='event_type',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('message', 'Message'), ('document', 'Document'), ('appointment', 'Appointment'), ('negotiation', 'Negotiation'), ('advice', 'Advice'), ('relocation', 'Relocation'), ('application', 'Application'), ('contract', 'Contract'), ('payment', 'Payment'), ('move', 'Move')], max_length=16),
        ),
        migrations.AddField(
            model_name='propertyapplication',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='winga_property.propertywingaassignment'),
        ),
        migrations.AddField(
            model_name='propertyapplication',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='winga_property.propertylisting'),
        ),
        migrations.AddField(
            model_name='propertyapplicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='winga_property.propertyapplication'),
        ),
        migrations.AddField(
            model_name='propertyapplicationverification',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='winga_property.propertyapplication'),
        ),
        migrations.AddField(
            model_name='propertylease',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='winga_property.propertyapplication'),
        ),
        migrations.AddField(
            model_name='propertylease',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='winga_property.propertylisting'),
        ),
        migrations.AddField(
            model_name='propertylease',
            name='renewal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='winga_property.propertylease'),
        ),
        migrations.AddField(
            model_name='propertyleasepayment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='winga_property.propertylease'),
        ),
        migrations.AddField(
            model_name='propertymoveworkflow',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_workflows', to='winga_property.propertylease'),
        ),
        migrations.AddIndex(
            model_name='propertyapplication',
            index=models.Index(fields=['applicant_principal', 'status'], name='winga_prope_applica_f7b945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyapplicationverification',
            unique_together={('application', 'check_kind')},
        ),
    ]
