# Generated by Django 5.1.6 on 2026-07-22 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winga_property', '0005_phase5_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOpsAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(max_length=64)),
                ('entity_type', models.CharField(max_length=32)),
                ('entity_id', models.UUIDField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('lease', 'Lease'), ('application', 'Application'), ('listing', 'Listing')], max_length=16)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('opened_by', models.CharField(db_index=True, max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('assigned_ops', models.CharField(blank=True, default='', max_length=128)),
                ('resolution', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='winga_property.propertylease')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='winga_property.propertylisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='winga_prope_status_1ca713_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyModerationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_principal', models.CharField(db_index=True, max_length=128)),
                ('reason', models.CharField(choices=[('fraud', 'Fraud'), ('misleading', 'Misleading'), ('duplicate', 'Duplicate'), ('inappropriate', 'Inappropriate'), ('other', 'Other')], max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=128)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='winga_property.propertylisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='winga_prope_status_97a098_idx')],
            },
        ),
    ]
