# Generated by Django 5.1.6 on 2026-07-19 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0001_map_foundation'),
        ('enterprise', '0002_winga_brokerage_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletFundingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_principal', models.CharField(db_index=True, max_length=128, unique=True)),
                ('priority', models.JSONField(blank=True, default=list, help_text='Ordered list of {kind, ref, label, enabled, confirm}')),
                ('auto_route', models.BooleanField(default=True)),
                ('require_confirmation', models.BooleanField(default=False)),
                ('auth_policy', models.CharField(choices=[('always', 'Always'), ('risk_based', 'Risk Based'), ('low_friction', 'Low Friction'), ('pin_only', 'Pin Only'), ('biometric_preferred', 'Biometric Preferred')], default='risk_based', max_length=32)),
                ('low_risk_threshold_minor', models.PositiveBigIntegerField(default=50000, help_text='Below this, risk-based auth may skip step-up')),
                ('merchant_overrides', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TapSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(db_index=True, max_length=48, unique=True)),
                ('channel', models.CharField(choices=[('static_qr', 'Static Qr'), ('dynamic_qr', 'Dynamic Qr'), ('payment_link', 'Payment Link'), ('invoice', 'Invoice'), ('remote_checkout', 'Remote Checkout'), ('pos', 'Pos'), ('softpos', 'Softpos'), ('nfc', 'Nfc'), ('wallet', 'Wallet'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('winga', 'Winga'), ('mobility', 'Mobility'), ('commerce_order', 'Commerce Order'), ('other', 'Other')], default='nfc', max_length=32)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('auth_required', 'Auth Required'), ('authorizing', 'Authorizing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('fallback', 'Fallback')], default='detected', max_length=24)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('payer_principal', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('selected_funding', models.JSONField(blank=True, default=dict)),
                ('auth_required', models.BooleanField(default=True)),
                ('auth_method', models.CharField(blank=True, default='', max_length=32)),
                ('auth_completed', models.BooleanField(default=False)),
                ('merchant_display', models.CharField(blank=True, default='', max_length=255)),
                ('terminal_capability', models.JSONField(blank=True, default=dict)),
                ('nfc_meta', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('payment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('receipt_code', models.CharField(blank=True, default='', max_length=48)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tap_sessions', to='acceptance.acceptanceintent')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tap_sessions', to='enterprise.merchant')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tap_sessions', to='acceptance.acceptanceterminal')),
            ],
            options={
                'indexes': [models.Index(fields=['payer_principal', 'status'], name='acceptance__payer_p_9f34be_idx'), models.Index(fields=['merchant', 'status'], name='acceptance__merchan_994fce_idx')],
            },
        ),
    ]
